PrestaShop/autoupgrade

AdminSelfUpgrade.php

http://forge.prestashop.com/browse/NM-241

[-] MO : Fix bug #NM-241, set maintenance for all shops

---

AdminSelfUpgrade.php

Prevent  a view to generate INSERT INTO statements

[-] MO: Fix PNM-3315, view content excluded from auto-backup

---

db/DbMySQLi.php

Report of https://github.com/PrestaShop/autoupgrade/pull/31

[-] MO: Fix report of #NM-305 https://github.com/PrestaShop/autoupgrade/pull/31

---

classes/Tools14.php
classes/Upgrader.php

:cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: :cancer: …

Add Tools14 copy to fix curl timeout issue

---

classes/Tools14.php

Got a bit carried away with the last PR... This one fixes it
Use https://github.com/PrestaShop/autoupgrade/pull/52/files?w=1 to see the diff
@maximebiloe Do you mind the indentation? The `if(!class_exists('Tools14',false))` was blowing my mind

Fix undefined class in Tools14

---

AdminSelfUpgrade.php

(and thanks @maximebiloe for the help with git ^^)

Wording update

---

AbstractLogger.php
AdminPreferences.php
AdminSelfTab.php
AdminSelfUpgrade.php
FileLogger.php
ajax-upgradetab.php
alias.php
autoupgrade.php
classes/AddConfToFile.php
classes/ConfigurationTest.php
classes/Tools14.php
classes/Upgrader.php
classes/pclzip.lib.php
classes/upgrade-17/CheckTests17.php
classes/upgrade-17/ConfigurationTest17.php
css/styles.css
db/Db.php
db/DbMySQLi.php
db/DbPDO.php
db/DbQuery.php
db/MySQL.php
functions.php
init.php
js/upgrade-1.7.js

Use the new system implemented in https://github.com/PrestaShop/PrestaShop/pull/7517

Allow to upgrade from 1.6 to 1.7 using the new upgrade system in 1.7 

---

AdminSelfUpgrade.php

Fix for non-linux system

---

AdminSelfUpgrade.php

Since: https://github.com/PrestaShop/PrestaShop/pull/7955/files
I'm sorry for this change..

Added variables js

---

.github/ISSUE_TEMPLATE/bug_report.md

New template for bug reports.
This ask for the user to provide the most details as possible to make the debug easier.

Create issue template for bug report

---

classes/Parameters/UpgradeConfigurationStorage.php
classes/TaskRunner/Miscellaneous/UpdateConfig.php
classes/Upgrader.php

Fixes #104
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/autoupgrade/127)

Reset archive filename when switching on channel

---

classes/Upgrader.php

Before merge, check https://api.prestashop.com/xml/channel.xml has PrestaShop 1.7 details.
Fixes #123 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/autoupgrade/126)

Remove use of channel17.xml

---

classes/UpgradePage.php
js/upgrade.js

Fix a duplicated label, and re-add a missing translated entry.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/autoupgrade/130)

Fix wording with replaced files

---

classes/UpgradePage.php
js/upgrade.js

Reverts PrestaShop/autoupgrade#130
Wrong destination branch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/autoupgrade/134)

Revert "Fix wording with replaced files"

---

composer.json

Reverts PrestaShop/autoupgrade#132
Wrong destination branch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/autoupgrade/135)

Revert "Force composer autoload to be appended"

---

autoupgrade.php
config.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/autoupgrade/142)

Bump version to 4.1.0

---

classes/Upgrader.php

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/autoupgrade/133)

Use a single folder for md5 files

---

autoupgrade.php
config.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/autoupgrade/156)

Bump to v4.1.1

---

classes/UpgradeSelfCheck.php

Fixes https://github.com/PrestaShop/PrestaShop/issues/10154
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/autoupgrade/157)

Check cURL without PS core

---

classes/TaskRunner/Upgrade/UpgradeFiles.php
classes/UpgradeTools/FileFilter.php
classes/UpgradeTools/FilesystemAdapter.php
tests/FilesystemAdapterTest.php

Reverts PrestaShop/autoupgrade#160
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/autoupgrade/164)

Revert "Fix ignored files outside shop folder"

---

autoupgrade.php
config.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/autoupgrade/168)

Bump version to 4.2.0

---

Readme.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/autoupgrade/173)

Update readme for php requirements

---

classes/UpgradeTools/CoreUpgrader/CoreUpgrader16.php
classes/UpgradeTools/SettingsFileWriter.php
views/templates/block/activityLog.twig
views/templates/block/channelInfo.twig
views/templates/block/checklist.twig
views/templates/block/rollbackForm.twig
views/templates/block/upgradeButtonBlock.twig
views/templates/block/versionComparison.twig
views/templates/main.twig

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/autoupgrade/176)

Fix wordings without domain

---

classes/UpgradePage.php
views/templates/block/channelInfo.twig
views/templates/block/checklist.twig

Per @LouiseBonnard's request: https://github.com/PrestaShop/PrestaShop/pull/10933
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/autoupgrade/179)

Fix wordings

---

classes/Upgrader.php

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/autoupgrade/180)

Suggest minor upgrades by default

---

classes/UpgradeTools/Translator.php
views/templates/block/activityLog.twig
views/templates/block/channelInfo.twig
views/templates/block/checklist.twig
views/templates/block/rollbackForm.twig
views/templates/block/upgradeButtonBlock.twig
views/templates/block/versionComparison.twig
views/templates/main.twig

Fixes #178
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/autoupgrade/181)

Remove trans_default_domain tag and rely on module translations only

---

js/upgrade.js

Fixes #185
Updating the config will trigger the page reload as before.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/autoupgrade/187)

Fix auto reload when updating the config

---

autoupgrade.php
config.xml
js/upgrade.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/autoupgrade/188)

Deploying v4.4.1 of the 1-click upgrade module

---

classes/UpgradePage.php
views/templates/main.twig

Fixes https://github.com/PrestaShop/PrestaShop/issues/11347

Do not define configuration values in JS (unused)

---

classes/TaskRunner/Upgrade/UpgradeComplete.php
classes/TaskRunner/Upgrade/UpgradeDb.php

Fixes https://github.com/PrestaShop/PrestaShop/issues/11142

Move cache clear earlier in the process

---

views/templates/block/checklist.twig
views/templates/block/upgradeButtonBlock.twig

Use raw trans to avoid &quot; being displayed

---

classes/UpgradeSelfCheck.php

Allow ipv6 to pass the maintenance check

---

classes/TaskRunner/Miscellaneous/UpdateConfig.php
classes/TaskRunner/Upgrade/AllUpgradeTasks.php
classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php

Fixes https://github.com/PrestaShop/PrestaShop/issues/11873

Do not reset theme anymore when already active (prevent hooks to be reset)

---

classes/UpgradeContainer.php
classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php
classes/UpgradeTools/ModuleAdapter.php
classes/UpgradeTools/SymfonyAdapter.php

Init Kernel on UpgradeDB when upgrading to 1.7

---

AdminSelfUpgrade.php

Display error when access is not granted

---

.gitignore
.php_cs.dist
AdminSelfUpgrade.php
classes/BackupFinder.php
classes/ChannelInfo.php
classes/Log/LegacyLogger.php
classes/Parameters/UpgradeConfiguration.php
classes/PrestashopConfiguration.php
classes/TaskRunner/Upgrade/AllUpgradeTasks.php
classes/TaskRunner/Upgrade/UpgradeNow.php
classes/Twig/Block/ChannelInfoBlock.php
classes/Twig/Block/RollbackForm.php
classes/Twig/Block/UpgradeButtonBlock.php
classes/Twig/Block/UpgradeChecklist.php
classes/Twig/Form/BackupOptionsForm.php
classes/Twig/Form/FormRenderer.php
classes/Twig/Form/UpgradeOptionsForm.php
classes/UpgradePage.php
classes/UpgradeSelfCheck.php
classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php
classes/UpgradeTools/CoreUpgrader/CoreUpgrader16.php
classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php
classes/UpgradeTools/ModuleAdapter.php
classes/UpgradeTools/SymfonyAdapter.php
classes/Upgrader.php
classes/ZipAction.php
tests/PrestaShopConfigurationTest.php
tests/ZipActionTest.php
tests/phpstan/bootstrap.php

After merge of #279, this PR will follow the coding standards of PrestaShop.
It also enable PrettyCI for the next contributions.

Enable php-cs-fixer on the project

---

classes/PrestashopConfiguration.php

Reverts PrestaShop/autoupgrade#322
Must be merged first on `dev`

Revert "Fix warning in 1.7 when settings file does not exist"

---

.travis.yml

| Description?  | Fix the `lastest` job in CI
| BC breaks?    | Nope
| Deprecations? | Nope
| Fixed ticket? | /
| How to test?  | CI is green

Make job with latest tag pass

---

Readme.md

| Description?  | Add travis badge status
| Fixed ticket? | 
| How to test?  |

Add travis badge status

---

docker-compose.yml
tests/docker-compose.yml

| Description?  | Install the database in docker-compose.yml files
| How to test?  | Travis is green.

Install the Database for tests

---

classes/UpgradeContainer.php

| Description?  | Fix bad directory name
| Fixed ticket? | 
| How to test?  |

Fix probably bad directory name

---

.github/workflows/php.yml
.travis.yml

| Description?  | Move PHPUnit Tests to GitHub Action. Also test on php5.6 and php7.2!
| Fixed ticket? |
| How to test?  | GA should pass

Move PHPUnit Tests to GA

---

.travis.yml

| Description?  | Test upgrades for PS1.7 with php7.1
| Fixed ticket? |
| How to test?  | Travis test should pass

Test upgrades for PS1.7 with php7.1

---

autoupgrade.php
config.xml

| Description?  | Bump version to 4.11.0
| Fixed ticket? | N/A
| How to test?  | N/A

Bump version to 4.11.0

---

Readme.md

| Description?  | Add some badges in README because it's shiny 🦄 
| Fixed ticket? | 
| How to test?  |

Add some badges in README

---

.github/workflows/php.yml
classes/TaskRunner/Upgrade/BackupDb.php
classes/Tools14.php
classes/UpgradeContainer.php
classes/UpgradePage.php
classes/UpgradeTools/ModuleAdapter.php
composer.json
composer.lock
tests/phpstan/Dockerfile
tests/phpstan/phpstan-PS-16.neon
tests/phpstan/phpstan.neon

| Description?      | For an unknown reason, phpstan tests didn't pass anymore. This PR aims to fix this by using the official phpstan docker container customized to use php 7.4.
| How to test?      | Tests must pass

Fix phpstan tests

---

autoupgrade.php
config.xml

| Description?      | Bump v4.12.0

Bump v4.12.0

---

classes/Log/Logger.php
classes/ZipAction.php

| Description?      | phpstan was failing, this PR fixes it
| How to test?      | Tests must pass

Fix phpstan

---

Readme.md

| Description?      | Replace Travis (deprecated) badge by GitHub Action Upgrade badge

Replace Travis (deprecated) badge by GitHub Action Upgrade badge

---

.github/workflows/nigthly_upgrade.yml

| Description?      | Use the right GCP secret keys defined in the PrestaShop Github organisation
| How to test?      | No test needed

Update GCP secret keys

---

.github/workflows/e2e_nightly_upgrade.yml

| Description?      | Don't run e2e workflow on push
| How to test?      | no

Don't run e2e workflow on push

---

.github/workflows/e2e_nightly_upgrade.yml
tests/e2e/scripts/getTargetVersions.js

| Description?      | Add branch to filename to push with nightly api
| How to test?      | no

Add branch to filename to push with nightly api

---

.github/workflows/nigthly_upgrade.yml

| Description?      | Fix filename for nightly cli to push on GCP
| How to test?      | no

Fix filename for nightly cli to push on GCP

---

tests/e2e/pages/BO/modules/autoupgrade/index.js

| Description?      | Wait For page to reload before putting it under maintenance
| How to test?      | all upgrades on nighthly should be green

Wait For page to reload before putting it under maintenance on e2e tests

---

views/templates/block/checklist.twig

| Description?      | Improve the link to PrestaShop  requirements
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/23832
| How to test?      | See issue

Improve link  to requirements

---

.github/get_results.php
.github/workflows/nigthly_upgrade.yml

| Description?      | This PR aims to add the nightly tests to both of the branches `dev` & `master` of the autoupgrade module

Add master branch to the nightly

---

.github/workflows/e2e_nightly_upgrade.yml

| Description?      | Add test branch to screenshot name
| How to test?      | no tests needed

Add test branch to screenshot name

---

classes/Twig/Block/UpgradeButtonBlock.php
views/templates/block/upgradeButtonBlock.twig

| Description?      | Display php Version 
| Fixed ticket?     | Fixes  https://github.com/PrestaShop/PrestaShop/issues/25656
| How to test?      | Open module see phpVersion

Display the current PHP version

---

tests/e2e/package-lock.json
tests/e2e/package.json

| Description?      | Upgrade prestashop_test_lib version to 0.0.14
| How to test?      | no tests needed

Upgrade prestashop_test_lib version to 0.0.14

---

css/styles.css
views/templates/block/upgradeButtonBlock.twig

| Description?      |  Bad display in autoupgrade module with PrestaShop version 1.7.8.0
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/25989
| How to test?      |  See issue
| Possible impacts? | No
Before :
After :

Fix bad display and uppercase to respect the project

---

upgrade/sql/8.0.0.sql

Everything is explained here PrestaShop/PrestaShop#25207
| Description?      | Please be specific when describing the PR. Every detail helps: What are you changing? Why?
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/25208

Drop column id_tax_rules_group in carrier table

---

upgrade/sql/8.0.0.sql

| Description?      | Removed Referrer (and associated) table
| Fixed ticket?     | Relative to PrestaShop/PrestaShop#27064
| How to test?      | N/A
| Possible impacts? | Upgrade to 8.0

Remove Referrer (and associated) table

---

autoupgrade.php
config.xml

| Description?      | Bump version 4.14.0 for release
| How to test?      | ~
| Possible impacts? | ~

Bump version 4.14.0

---

classes/Twig/Block/UpgradeChecklist.php
classes/UpgradeSelfCheck.php
views/templates/block/checklist.twig

| Description?      | Check last version of the module
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/15194 and https://github.com/PrestaShop/PrestaShop/issues/26066
| How to test?      | You need to change the version number to see if the message is displayed correctly.

Check last version module

---

upgrade/sql/8.0.0.sql

| ----------------- | -------------------------------------------------------
| Description?      | Add missing hooks actionCustomerLogout After Before and displayCheckoutSummaryTop
| Category?         | IN
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/19894 AND https://github.com/PrestaShop/PrestaShop/issues/15594
| How to test?      | Install a new shop and made an upgrade to 8.0.0 after check the hook
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Add missing hooks actionCustomerLogout & displayCheckoutSummaryTop

---

.github/workflows/e2e_nightly_upgrade.yml
.github/workflows/nigthly_upgrade.yml

| Description?      | Fix setup GCP on workflows to push results on nightly (relative to https://github.com/PrestaShop/PrestaShop/commit/a38316f51817cef35280a5aa8668c71b214ce726)
| How to test?      | no tests needed

Fix setup GCP on workflows to push results on nightly

---

classes/Twig/Block/UpgradeChecklist.php
classes/UpgradeSelfCheck.php
views/templates/block/checklist.twig

| Description?      | Fix the maintenance mode check process
| Fixed ticket?     | Fixes [#25642](https://github.com/PrestaShop/PrestaShop/issues/25642)
| How to test?      | see issue

Check the maintenance mode activation

---

upgrade/sql/8.0.0.sql

| Description?      | Adds database column for related change - https://github.com/PrestaShop/PrestaShop/pull/27292
| How to test?      | To be tested at the same time as PrestaShop/PrestaShop#27292

Add category additional description column during upgrade

---

upgrade/sql/8.0.0.sql

| Description?      | Add new https://github.com/PrestaShop/PrestaShop/pull/27437 hook during upgrade
| How to test?      | Install a new shop, make an upgrade to 8.0.0, check the hook is in DB
| Possible impacts? | No

Add displayCheckoutBeforeConfirmation hook

---

autoupgrade.php
config.xml

| Description?      | Bump version 4.15.0 for release
| How to test?      | ~
| Possible impacts? | ~

Bump to 4.15.0

---

upgrade/sql/1.7.7.0.sql

| Description?      | Add SQL Query relative to Fuzzy Search. Configuration was introduced in 1.7.7.0 by @Lathanao in PrestaShop/PrestaShop#14428
| Fixed ticket?     | Fixes PrestaShop/PrestaShop#27823
| How to test?      | Cf. PrestaShop/PrestaShop#27823

Add SQL Query relative to Fuzzy Search

---

upgrade/sql/8.0.0.sql

| Description?      | Add hook actionGetAlternativeSearchPanels for 8.0 upgrade
Related to https://github.com/PrestaShop/PrestaShop/pull/28504

Hook for alternative search panel

---

upgrade/php/ps_800_update_tab_lang.php
upgrade/php/ps_update_tab_lang.php
upgrade/sql/8.0.0.sql

| Description?      | Adds SQL queries to update the `ps_feature_flag` table on upgrade to PrestaShop v8
| Fixed ticket?     | https://github.com/PrestaShop/PrestaShop/issues/28505
| How to test?      | This PR is linked to the feature flag PR: [#28594 ](https://github.com/PrestaShop/PrestaShop/pull/28594)

Add 8.0.0 feature flag update sql queries

---

upgrade/sql/1.6.1.0.sql
upgrade/sql/1.6.1.7.sql
upgrade/sql/1.7.0.0.sql

| Description?      | Fix for ticket 27184
| Fixed ticket?     | Fixes PrestaShop/PrestaShop#27184
| How to test?      | Upgrade from 1.6 to 1.7 succeeds without warnings.
| Possible impacts? | Nothing outside the upgrade process

Upgrade process will not stop due to existing hooks

---

upgrade/sql/8.0.0.sql

| Description?      | Remove Tab for Referrers Page
| Fixed ticket?     | Fixes PrestaShop/PrestaShop#27064
| How to test?      | Cf. PrestaShop/PrestaShop#27064

Remove Tab for Referrers Page

---

upgrade/sql/8.0.0.sql

| Description?      | Update quick access link for orders
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/27513
| How to test?      | Check if the link is good.

Update quick access link for orders

---

upgrade/sql/1.7.8.7.sql

| Description?      | As a hotfix (https://github.com/PrestaShop/autoupgrade/commit/a52214e4afc10e0263828467af88293f1b8b6e23)  has been made directly to the master branch for release 4.14.2, this PR aims to bring this hotfix to the dev branch

Cherry pick a52214e to dev

---

views/templates/block/checklist.twig
views/templates/block/upgradeButtonBlock.twig

| Description?      | This PR puts back missing raw twig helper
| Fixed ticket?     | Fixes [#29755](https://github.com/PrestaShop/PrestaShop/issues/29755)
| How to test?      | see steps in [#29755](https://github.com/PrestaShop/PrestaShop/issues/29755)

Fix broken wording

---

upgrade/sql/8.0.0.sql

| Description?      | Need this SQL upgrade for this PR: https://github.com/PrestaShop/PrestaShop/pull/27952
| Fixed ticket?     | https://github.com/PrestaShop/PrestaShop/issues/28748
| How to test?      | See https://github.com/PrestaShop/PrestaShop/pull/27952
| Possible impacts? | None

Adding the PATCH method to the REST API (webservices)

---

tests/fixtures/AppKernelExample.php.txt
upgrade/install-4.10.1.php
views/templates/hook/dashboard_zone_one.tpl

| Description?      | Update header licence
| How to test?      | just go through this PR code for quality
| Possible impacts? | no

Update licence header

---

upgrade/sql/8.1.0.sql

| Description?      | Autoupgrade PR for https://github.com/PrestaShop/PrestaShop/pull/29797

Add sitemap hook on upgrade

---

upgrade/sql/8.1.0.sql

| Description?      | Allow to configure, if order should switch to backorder. Autoupgrade PR for https://github.com/PrestaShop/PrestaShop/pull/29753.

Allow to configure, if order should switch to backorder

---

classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php

| Description?      | Typo on module dir constant
| Fixed ticket?     | none
| How to test?      | upgrade

Typo on module dir constant

---

autoupgrade.php

| Description?      | Agreed with othe project members that v4.15 is only for 1.7+
| Fixed ticket?     | n/a
| How to test?      | no need

Minimum compat for 4.15 is 1.7

---

README.md

| Description?      | Update README for 4.15.0

Update README for 4.15.0

---

classes/Twig/Block/UpgradeChecklist.php
classes/UpgradeSelfCheck.php
views/templates/block/checklist.twig

| Description?      | Please be specific when describing the PR. Every detail helps: What are you changing? Why?
| Fixed ticket?     | Fixes PrestaShop/PrestaShop#29758 PrestaShop/PrestaShop#25642
| How to test?      | Please see PrestaShop/PrestaShop#29758 & PrestaShop/PrestaShop#25642

Fix maintenance check

---

classes/TaskRunner/Miscellaneous/UpdateConfig.php
classes/UpgradePage.php
classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php
classes/UpgradeTools/CoreUpgrader/CoreUpgrader80.php

| Description?      | Fix some strings
| Fixed ticket?     | Partially fixes https://github.com/PrestaShop/PrestaShop/issues/30008
| How to test?      | Please see https://github.com/PrestaShop/PrestaShop/issues/30008

Fix translations

---

upgrade/sql/8.1.0.sql

| Description?      | Adds a new hook added in https://github.com/PrestaShop/PrestaShop/pull/29781/

Add actionGenerateDocumentReference hook

---

autoupgrade.php
config.xml

Release 4.16.0

---

upgrade/sql/8.0.1.sql

| Description?      | Uninstall from the database the module welcome
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/31659
| Sponsor company   | Prestashop SA
| How to test?      | See https://github.com/PrestaShop/PrestaShop/issues/31659

Uninstall from the database the module welcome

---

upgrade/sql/8.1.0.sql

| Description?      | Update SQL file with data from PR https://github.com/PrestaShop/PrestaShop/pull/27927 and https://github.com/PrestaShop/PrestaShop/pull/31130
| BC breaks?        |no 
| Fixed ticket?     | none
| How to test?      | PrestaShop should install without error with this module

update 8.1.0 sql script

---

upgrade/php/ps_remove_controller_tab.php

| Description?      | I changed the prefix in the SQL query, so the extra underscore was removed.
| Fixed ticket?     | Fixes #31219 https://github.com/PrestaShop/PrestaShop/issues/31219 
| Sponsor company   | Prestaworks AB
| How to test?      | Follow instruction in issue

Fix issue with bad table prefix

---

upgrade/sql/9.0.0.sql

| Description?      | Added new hook from PR 31294 to autoupgrade script
| Sponsor company   | Prestaworks AB
| Related PRs | https://github.com/PrestaShop/PrestaShop/pull/31294

New hook for performing actions when address change on cart

---

upgrade/sql/8.1.0.sql

| Description?      | Adds a new hook added in https://github.com/PrestaShop/PrestaShop/pull/31691
| Fixed ticket?     |
| Sponsor company   |
| How to test?      | see if the hook is in the upgraded version

Add actionAdminMenuTabsModifier hook

---

.github/get_matrix.php
.github/workflows/e2e_nightly_upgrade.yml
.github/workflows/nightly_upgrade.yml
tests/e2e/scripts/getTargetVersions.js

| Description?      | Nightly : Migrate from nightly.prestashop.com to nightly.prestashop-project.org
| How to test?      | N/A

Nightly : Migrate from nightly.prestashop.com to nightly.prestashop-project.org

---

upgrade/php/execute_sql_if_table_exists.php
upgrade/php/ps_1770_preset_tab_enabled.php
upgrade/sql/1.7.7.0.sql
upgrade/sql/8.0.0.sql

| Description?      | Fix various bug in migration scripts
| How to test?      | Run an autoupgrade from a 1.7 DB to 8.0.1, especially with disable modules

Fix migration issues

---

upgrade/sql/8.1.0.sql

| Description?      | Add id_employee in order_payment table
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/33108, Fixes https://github.com/PrestaShop/PrestaShop/issues/33118, Fixes https://github.com/PrestaShop/PrestaShop/issues/33238

Add id_employee in order_payment table

---

autoupgrade.php
config.xml

| Description?      | Bump version to 4.16.1
| Type?             | 
| BC breaks?        | 
| Deprecations?     | 

Bump version to 4.16.1

---

classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php
upgrade/php/migrate_tabs_17.php

| Description?      | Fix for issue 27087
| Fixed ticket?     | Related to PrestaShop/PrestaShop#27087.
| How to test?      | See Issue for details.

Fix line not compatible with PHP < 7

---

classes/UpgradePage.php

| Description?      | Adds small hint about debug mode.
| How to test?      | No need to test, merge right away.

Add upgrade helptext

---

classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php
classes/UpgradeTools/CoreUpgrader/CoreUpgrader80.php
classes/UpgradeTools/CoreUpgrader/CoreUpgrader81.php

| Description?      | Add more info to autoupgrade process to better see what is going on.
| How to test?      | I think it's not needed to test it.

Add more info to autoupgrade process

---

classes/UpgradeTools/ModuleAdapter.php

| Description?      | The goal of this PR is to be able to use a given module zip instead of downloading it from Addons.<br><br>This will help module developpers to test their new module version when upgrading PS
| Sponsor company   | N/A
| How to test?      | Use this branch for autoupgrade. On your shop, Install a module in a version, get the zip of a higher version of this module.<br>Put this higher version in ```_PS_ADMIN_DIR_/autoupgrade/modules_MODULE_NAME_.zip```<br>Launch an autoupgrade<br><br>Even if this version doesn't exist on Addons, your module will be upgraded …

Upgrade module from local source

---

upgrade/sql/9.0.0.sql

| Description?      | Adds hooks from presenter PRs - https://github.com/PrestaShop/PrestaShop/pull/32653, https://github.com/PrestaShop/PrestaShop/pull/32652, https://github.com/PrestaShop/PrestaShop/pull/32634
| How to test?      | Tests green, does not need QA.

Add presenter hooks

---

upgrade/sql/8.1.2.sql

| Description?      | Fixes security tabs wordings for people that started on 8.0.0-8.1.1
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/33763
| How to test?      | Install 8.0.0, upgrade to 8.1.2 and follow steps in this issue - https://github.com/PrestaShop/PrestaShop/issues/33763

Fix tab wordings

---

autoupgrade.php
config.xml

| Description?      | Bump to 4.16.3
| How to test?      | Indicate how to verify that this change works as expected.

bump to 4.16.3

---

README.md

| Description?      | Add mention to release process in README
| How to test?      | No need for tests

Add mention to release process in README

---

README.md

| Description?      | Improve README: Better titles structure and update link to devdoc

Improve README: Better titles structure and update link to devdoc

---

upgrade/sql/8.1.2.sql

| Description?      | Add 2 new hooks for 8.1.2

Add 2 new hooks for 8.1.2

---

autoupgrade.php
config.xml

| Description?      | 
| Type?             | 
| BC breaks?        | 
| Deprecations?     | 

Bump version to 4.16.5

---

autoupgrade.php
js/upgrade.js
views/templates/block/upgradeButtonBlock.twig

| Description?      | Removes the usage of pre 1.6 link style, using tab as a parameter.

Remove tab link

---

.github/workflows/e2e_nightly_upgrade.yml
.github/workflows/nightly_upgrade.yml
.github/workflows/php.yml
.github/workflows/upgrade.yml

| Description?      | Please check the fixed ticket.
| Fixed ticket?     | PrestaShop/PrestaShop/issues/34538
| Sponsor company   | Your company or customer's name goes here (if applicable).
| How to test?      | PHP tests pass without warning of deprecated node12

Upgrade github actions to v3

---

upgrade/php/update_null_values.php
upgrade/sql/8.1.3.sql

| Description?      | This PR repeats the work of the PR https://github.com/PrestaShop/autoupgrade/pull/605, adding a php function call
| Fixed ticket?     | Fixes #https://github.com/PrestaShop/PrestaShop/issues/33371, Fixes #https://github.com/PrestaShop/PrestaShop/issues/25996, Fixes #https://github.com/PrestaShop/PrestaShop/issues/22862, Fixes #https://github.com/PrestaShop/PrestaShop/issues/22386, Fixes #https://github.com/PrestaShop/PrestaShop/issues/22215
| How to test?      | see below
To verify that the script has been executed, there are several solutions:
- if 8.1.3 is …

Normalize NULL data in database

---

autoupgrade.php
config.xml

| Description?      | Bump version number to 5.0.0. This new version must be a new major version because it contains breaking changes: for example the change of minimum PrestaShop version (1.7 instead of 1.6) and the removal the migration scripts for versions lower than 1.7
| Deprecations?     |
| How to test?      | No need to test

Bump version number to 5.0.0

---

upgrade/sql/9.0.0.sql

| Description?      | These values are related to the debug cookie feature
| Fixed ticket?     | Related to https://github.com/PrestaShop/PrestaShop/pull/32809
| Sponsor company   | --

Add debug cookie default configuration values

---

autoupgrade.php
config.xml

| Description?      | 
| Sponsor company   | ~
| How to test?      | ~

Bump version 5.0.1

---

.github/workflows/nightly_upgrade.yml

| Description?      | Fix nightly (old warning from 2022: The `set-output` command is deprecated and will be disabled soon. )
| How to test?      | Result -> https://github.com/PrestaShop/autoupgrade/actions/runs/8520284904

Fix nightly

---

upgrade/sql/9.0.0.sql

| Description?      | Update the ean13 field to a varchar(20) for PR https://github.com/PrestaShop/PrestaShop/pull/35697.
| How to test?      | CI 🟢

Update the ean13 field

---

upgrade/sql/9.0.0.sql

| Description?      | Adds new hook introduced in https://github.com/PrestaShop/PrestaShop/pull/34875.
| How to test?      | Run query manually.

Add actionValidateCartRule hook

---

autoupgrade.php
config.xml

| Description?      | Bump version 5.0.2

Bump version 5.0.2

---

.github/action.yml
.github/check_url.sh
docker-compose.yml

| Description?      | Improved URL verification step in github action, with addition of timeout, so as not to wait 6 hours for the end of the github workflow

Improved URL verification step in github action, with addition of timeout

---

autoupgrade.php
config.xml
upgrade/install-5.0.3.php

| Description?      | After the creation of the 5.x branch, we want to merge its content into the `master` branch so we can publish the new version.
| Type?             | merge
| Sponsor company   | /
| How to test?      | /

Prepare release of 5.0.3

---

classes/TaskRunner/Miscellaneous/UpdateConfig.php

| Description?      | add new check between the xml and zip version for local upgrade
| How to test?      | Use XML in another version. See alert

add new check between the xml and zip version for local upgrade

---

.github/workflows/ui-test.yml

| Description?      | Update last version of PS 8.1
| How to test?      | CI is :green_apple:

Update last version of PS 8.1

---

.github/workflows/ui-test.yml

| Description?      | UI tests - Fix minor channel to upgrade from 8.0
| Sponsor company   | @PrestaShopCorps
| How to test?      | Ci is :green_apple:

UI tests - Fix minor channel to upgrade from 8.0

---

.github/workflows/ui-test.yml
tests/UI/campaigns/shopVersion/01_CheckVersion.spec.ts
tests/UI/campaigns/shopVersion/02_checkVersionInDatabase.spec.ts
tests/UI/package-lock.json

| Description?      | Add matrice of 1.7.8.0 ~ 1.7.8.10 (minor) on PHP 7.2 ~ 7.4
| How to test?      | IUI tests are :green_apple:

UI tests - Add matrice of 1.7.8.0 ~ 1.7.8.10 to 1.7.8.11 (minor) on PHP 7.2 ~ 7.4

---

views/templates/block/footer.twig
views/templates/main.twig

| Description?      | Add Data transparency link in footer
| How to test?      | See footer in UI

Add Data transparency link in footer

---

.github/workflows/ui-test.yml

| Description?      | Update matrice to run sanity tests on last version of each minor
| How to test?      | CI is :green_apple:

UI tests - Update matrice to run sanity tests on last version of each minor

---

upgrade/sql/8.1.0.sql
upgrade/sql/8.1.1.sql

| Description?      | Fix authorized_application request

Fix 8.1.0 sql 

---

.github/workflows/ui-test.yml
.github/workflows/ui-test/nightly.json

| Description?      | Nightly : Fixed quote & Github Action dependency
| How to test?      | CI is :green_circle:

Nightly : Fixed quote & Github Action dependency

---

.github/workflows/ui-test.yml

| Description?      | Nightly: Fixed name of the artifact
| How to test?      | CI is :green_circle:

Nightly: Fixed name of the artifact

---

.github/workflows/extract-translations.yml
views/templates/block/activityLog.twig

| Description?      | Last CI about translation extractor fails. This PR is for fixing it.
| How to test?      | ---

Fix: extractor translation

---

.github/workflows/ui-test.yml

| Description?      | Update actions checkout version to V4
| How to test?      | Ci is :green_apple:

UI tests - Update actions checkout version to V4

---

.github/workflows/ui-test.yml

| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Nightly : Fixed path of the file (for the version in Backend)
| Category?         | TE
| How to test?      | CI is :green_circle: 
| Fixed issue or discussion?     | N/A
| Related PRs       | N/A

Nightly : Fixed path of the file (for the version in Backend)

---

autoupgrade.php
config.xml

| Description?      | Bump module version from 5.0.3 to 6.0.0

Bump module version from 5.0.3 to 6.0.0

---

.github/workflows/ui-test/nightly.json

| Description?      | Fix the nightly
| How to test?      | Ci is :green_apple:

UI tests - Fix the nightly

---

.github/workflows/build-release.yml
.github/workflows/publish.yml

| Description?      | The creation of module zip is failing for several reasons. I.e because we run a dev dependency after a `composer install` with production only deps.
| Sponsor company   | /
| How to test?      | Test releases must succeed, see https://github.com/Quetzacoalt91/autoupgrade/releases/tag/v6.0.0-test.2

Fix build of module

---

upgrade/sql/9.0.0.sql

| Description?      | Add SQL from "Remove doctrine command from install process" PR in CORE https://github.com/PrestaShop/PrestaShop/pull/36233

Add SQL from "Remove doctrine command from install process" PR in CORE

---

translations/ModulesAutoupgradeAdmin.en.xlf

This pull request contains the default catalogue updates introduced in the branch [enchancement/extractor-translation]

Translation catalog update

---

.github/workflows/ui-test.yml
.github/workflows/upgrade.yml

| Description?      | Add draft filter in actions
| Type?             |improvement

Add draft filter in actions

---

classes/UpgradePage.php
js/upgrade.js
views/templates/block/activityLog.html.twig
views/templates/block/postUpdateChecklistBlock.html.twig
views/templates/main.html.twig

| Description?      | Update post update checklist

Update post update checklist

---

js/upgrade.js
views/templates/block/postRestoreChecklistBlock.html.twig
views/templates/main.html.twig

| Description?      | New restore checklist

New restore checklist

---

classes/Twig/Block/UpgradeButtonBlock.php
classes/UpgradePage.php
controllers/admin/AdminSelfUpgradeController.php
js/upgrade.js
storybook/stories/UpgradeButton.stories.js
views/templates/block/upgradeButtonBlock.html.twig

| Description?      | Remove manual mode. This was never finalized, and made it possible to carry out certain specific tasks of the upgrade
| How to test?      | No changes to interface and behavior

Remove manual mode

---

classes/Analytics.php
classes/Parameters/UpgradeConfiguration.php
classes/Parameters/UpgradeConfigurationStorage.php
classes/Progress/CompletionCalculator.php
classes/Task/Miscellaneous/UpdateConfig.php
classes/Task/Upgrade/BackupDb.php
classes/Task/Upgrade/BackupFiles.php
classes/Twig/Form/FormRenderer.php
classes/UpgradeContainer.php
classes/UpgradePage.php
classes/UpgradeSelfCheck.php
classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php
controllers/admin/AdminSelfUpgradeController.php

| Description?      | Updating the upgrade configuration system
| How to test?      | The different configurations work the same way as before. It is now possible to add configurations to a CLI upgrade

Improve the upgrade configuration system

---

js/upgrade.js

| Description?      | Improve js error handler. All errors now appear in the errors card. The browser alert offering a rollback on error is removed in favor of the rollback form.
| Deprecations?    | no
| How to test?      | See below
On an update, verified that all errors are now in the errors card
- Malformed JSON result
- Timeout
- HTTP Code 4xx / 5xx
- Upgrade errors

Improve js error handler

---

autoupgrade.php
config.xml

| Description?      | Bump version to 6.1.0
| Type?             | improvement 

Bump version to 6.1.0

---

js/dashboard.js
js/sentry.js
js/upgrade.js

| Description?      | Standardization of the JS format
| How to test?      | Interface / Upgrade should work the same as before

Standardization of the JS format

---

upgrade/sql/9.0.0.sql

| Description?      | Add missing feature flags for v9

Add missing feature flags for v9

---

classes/State.php
classes/UpgradeContainer.php
classes/UpgradePage.php
classes/Upgrader.php
controllers/admin/AdminSelfUpgradeController.php

| Description?      | Correction of an error when installing the module on a version of prestashop currently under development
| Fixed ticket?     | https://github.com/PrestaShop/PrestaShop/issues/36773
| How to test?      | https://github.com/PrestaShop/PrestaShop/issues/36773

Correction of an error when installing the module on a version of prestashop currently under development

---

classes/Task/Miscellaneous/CheckFilesVersion.php

| Description?      | In Version comparison, the PrestaShop Original version section shows 0 modifications have been detected, even there are.
| How to test?      | Show more than 0 modifications

bug changedFileList is cleared showing 0 modifications have been detected

---

autoupgrade.php
config.xml

| Description?      | Bump to version 6.2.0
| Sponsor company   | /
| How to test?      | Module version is now 6.2.0 on the module manager

Bump to v6.2.0

---

upgrade/sql/9.0.0.sql

| Description?      | PR to update DB structure after https://github.com/PrestaShop/PrestaShop/pull/35882.

Unify varchar limits

---

classes/Twig/Block/UpgradeChecklist.php
classes/UpgradeSelfCheck.php
controllers/admin/AdminSelfUpgradeController.php
views/templates/block/checklist.html.twig

| Description?      | Certain requirements disappeared with v7, I also have a function to recover the wording to unify it between the CLI and the web version. Withdrawal of the requirement "checkMissingFiles"
| How to test?      | Non-regression tests on the checklist

Improve requirements for v7.0.0
