PrestaShop/autoupgrade

- db/DbQuery.php
MO: fix this bug when using php7.1 :
PHP Fatal error: Uncaught Error: [] operator not supported for strings in /modules/autoupgrade/db/DbQuery.php:70
> Fix bug when using php7.1

- AdminSelfUpgrade.php
When a **broken** symbolic link exists on the Filesystem, the module tries to backup it before proceeding with the upgrade.
Because the link destination does not exist, there is nothing to save. This PR asks the module to bypass this case.
Fixes http://forge.prestashop.com/browse/BOOM-4957
> Continue on broken symlink in directory listing

- AdminSelfUpgrade.php
On IIS (Windows Server) the admin/autoupgrade-directory would not be writable. This is due to the drive-letter being undercase on _PS_ADMIN_DIR_ and uppercase on _PS_ROOT_DIR_. See tracker issue PNM3927 for more info.
> add realpath() to $this->adminDir for IIS

- classes/Parameters/UpgradeConfigurationStorage.php
- tests/UpgradeConfigurationTest.php
This PR covers a case where the data saved in files may change between two release. It appeared upgrading a shop under 1.6 was impossible, because of download issues.
From now, even if the data does not exist in the saved content, it will be declared in the Configuration class.
Fixes http://forge.prestashop.com/browse/BOOM-4960
> Always load default conf data before saved conf files

- Readme.md
- ajax-upgradetabconfig.php
- classes/Log/LegacyLogger.php
In the previous versions, the files has to be ALWAYS generated in the admin folder.
With the refacto, it appeared they could be found in the module folder, for instance when you call the file `cli-upgrade.php`.
This PR
* fixes the definition of _PS_ADMIN_DIR_
* refactoed (again) the init file
* fixes the `--dir` option in the Readme
* Adds carriage returns in the log
> Avoid files to be generated outside the admin folder

- classes/ZipAction.php
On huge servers with many files to backup but limited storage, "no space left" errors may occurs.
When it happened, the process did not stop and was still trying to add even more files to the zip file.
With this PR, we stop the process as we can't go further.
ping @LouiseBonnard for string review.
> Stop upgrade process if zip file can't be closed

- classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php
- classes/UpgradeTools/CoreUpgrader/CoreUpgrader16.php
- classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php
- classes/UpgradeTools/ModuleAdapter.php
It appeared disabling modules triggered many errors during the upgrade file, as we were trying to find which one had to be disabled. To find these, we had to instantiate them, generally throwing errors on the new core.
From this PR, we try to use the 1.6 method, which only reads the config.xml files.
> Disable modules with 1.6 method

- classes/UpgradeTools/CoreUpgrader/CoreUpgrader16.php
Starting with PS 1.6.1.20, mcrypt is mandatory. The related keys are also needed in the settings file if the merchants wants to keep its shop accessible.
This PR adds the key generation during the upgrade to another 1.6 version.
> Set RIJNDAEL keys when mcrypt is available

- classes/Twig/Block/UpgradeChecklist.php
- classes/UpgradeContainer.php
- classes/UpgradeSelfCheck.php
- views/templates/block/checklist.twig
Some checks are done by PrestaShop and can be found in the AdminInformation page.
Some errors found during the upgrade were caused by this requirements not satisfied, so we added them to the preliminary checklist.
**Note:** The performance will decrease with this PR, as it checks the folders permissions.
OK:
Non-OK:
> Use Prestashop requirements in Upgrade check list

- AdminSelfUpgrade.php
This PR is a backport of #88 for module compatible with old versions of PrestaShop
> Starting with PS 1.6.1.20, mcrypt is mandatory. The related keys are also needed in the settings file if the merchants wants to keep its shop accessible.
This PR adds the key generation during the upgrade to another 1.6 version.
> [3.x] Set RIJNDAEL keys when mcrypt is available

- classes/TaskRunner/AllUpgradeTasks.php
- classes/TaskRunner/Upgrade/Download.php
We currently have an issue with md5 check on 1.6 releases.
The issue was properly detected, but the Travis job wasn't set in failure. This PR fixes the issue.
> Detect error step

- classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php
- classes/UpgradeTools/CoreUpgrader/CoreUpgrader16.php
- classes/UpgradeTools/SettingsFileWriter.php
- tests/SettingsFileWriterTest.php
Tag `<?php` was missing in generated config/settings.php files...
We used a generated settings file as a comparison, to check files are properly created.
> Fix missing opening <?php in settings file

- classes/TaskRunner/Upgrade/Unzip.php
This PR covers a case where a missing `prestashop/` folder in a release ZIP will drop the whole shop.
> Check subfolder prestashop/ exists in 1.6 releases

- views/templates/block/upgradeButtonBlock.twig
There were some misunderstanding about the "local archive" of the module. Users didn't understand they had to write the destination version of PrestaShop in a field.
This could get a validator later, but first we just add a placeholder to give an example of expected value.
> Add placeholder for PrestaShop version

- classes/TaskRunner/Upgrade/CleanDatabase.php
It seems starting with PrestaShop 1.7.3.0, we need to have empty but localized configuration data. See http://forge.prestashop.com/browse/BOOM-5982 for more details.
This conflicts with the integrity check from the upgrade.
> Do not clean empty conf values

- classes/TaskRunner/Rollback/RestoreDb.php
- classes/TaskRunner/Rollback/RestoreFiles.php
- classes/TaskRunner/Rollback/Rollback.php
- classes/UpgradeContainer.php
Restoring a shop should not use the core during the process, because it is obviously unstable.
This PR removes all calls to the core, but keeps the autoloader when we handle the database step.
> Remove links to PS core during restoration

- views/templates/block/upgradeButtonBlock.twig
Even if the upgrade configuration was properly saved, the latest archive of the list was always selected.
> Fix display of selected archive

- classes/TaskRunner/Upgrade/RemoveSamples.php
- classes/TaskRunner/Upgrade/UpgradeFiles.php
- classes/UpgradeTools/FilesystemAdapter.php
- tests/FilesystemAdapterTest.php
- views/templates/block/upgradeButtonBlock.twig
While testing with the option "Local folder", it appeared the given folder was incorrect. Following the text made the shop being deleted. :fearful: 
This PR fixes the directory displayed, and adds a check verifying we have a PrestaShop release in a given folder. This will prevent an upgrade to run if the content is copied in a subfolder for instance.
> Avoid starting the upgrade when the source folder is not a PrestaShop release

- classes/TaskRunner/Upgrade/BackupDb.php
Fixes #106 
The module was trying to guess what value to store in the backup when it was empty, depending on the table structure.
Just stick to the original value, before escape. If it was NULL, store it directly as-is in the backup file.
> Store NULL is backups when NULL is in DB

- classes/UpgradeTools/FilesystemAdapter.php
Files like .htaccess must be stored in backups, or restores won't bring shops at their previous state.
> Store hidden files in backups

- composer.json
To avoid core libraries to be overridden, we append the module autoloader instead of preppending it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/autoupgrade/132)
> Force composer autoload to be appended

- classes/UpgradeTools/CoreUpgrader/CoreUpgrader16.php
Fixes #140 
The class defined in the file `CoreUpgrader16` is `Tools14`. Calling `Tools` instead was throwing errors during an upgrade.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/autoupgrade/141)
> Fix undefined class Tools

- composer.json
Reverts PrestaShop/autoupgrade#136
Saw on PrestaShop 1.6.0.4. Fixes 
```
Fatal error: require(): Failed opening required '/var/www/html/' (include_path='.:/usr/local/lib/php') in /var/www/html/classes/PrestaShopAutoload.php on line 121
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/autoupgrade/144)
> Revert "Force composer autoload to be appended"

- classes/TaskRunner/Rollback/RestoreDb.php
On the first versions of PS 1.6, the file `bootstrap.php` does not exist. We add a check to prevent a fatal error during a restore.
To be done later: Implement a method checking and requiring a file for us.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/autoupgrade/145)
> Check bootstrap.php before require

- classes/TaskRunner/Upgrade/UpgradeFiles.php
- classes/UpgradeTools/FileFilter.php
- classes/UpgradeTools/FilesystemAdapter.php
- tests/FilesystemAdapterTest.php
Fixes https://github.com/PrestaShop/autoupgrade/issues/159
When checking the files to ignore during the process, using the temporary folder where release are stored make the results wrong. That was caused by a file path strict check from the filesystem root.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/autoupgrade/160)
> Fix ignored files outside shop folder

- AdminSelfUpgrade.php
- autoupgrade.php
Avoid "Already registered autoload class" when used with symlink
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/autoupgrade/166)
> Use _PS_ROOT_DIR_ in autoload paths

- AdminSelfUpgrade.php
- classes/TaskRunner/Upgrade/UpgradeComplete.php
- classes/UpgradeSelfCheck.php
- views/templates/block/checklist.twig
This PR makes the PrestaShop requirements optional, because of known issues on the Information Page
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/autoupgrade/167)
> Allow users to ignore the PrestaShop requirements which can be incomplete

- classes/TaskRunner/Upgrade/UpgradeFiles.php
- classes/UpgradeTools/FileFilter.php
- classes/UpgradeTools/FilesystemAdapter.php
- tests/FilesystemAdapterTest.php
Duplicates #160 
Recreated to be on the proper branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/autoupgrade/165)
> Ignored files incorrect outside root

- classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php
Fixes #158, where some classes could not be found because not handled by the core autoloader.
From now, we also load the install autoloader to use the classes present in the install/ folder.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/autoupgrade/163)
> Use install autoloader for classes in install/

- Readme.md
- autoupgrade.php
- classes/UpgradeTools/Translator.php
- composer.json
Fixes #170 
This PR fixes the syntax errors on very old versions of PHP, but prevent its installation on the concerned shops.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/autoupgrade/171)
> Prevent installation on old PHP versions

- classes/Tools14.php
- classes/Upgrader.php
Reported in https://github.com/PrestaShop/PrestaShop/issues/11409
The download of the PrestaShop release was stored in the memory, which threw exception on small configuration. This updates the process to use a buffer instead.
> Avoid storing whole file content in memory

- classes/PrestashopConfiguration.php
- tests/PrestaShopConfigurationTest.php
- tests/fixtures/AppKernelExample.php.txt
Starting with PrestaShop 1.7.5.0, the version can be found as a constant in the `AppKernel`. To allow the module to work properly when we will upgrade from this version, we must handle it now.
> Handle PrestaShop version in AppKernel

- tests/ErrorHandlerTest.php
This PR removes unexpected output to be displayed while running php tests.
**Before:**
```
$ php vendor/phpunit/phpunit/phpunit tests
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.
.........{"nextQuickInfo":[],"nextErrors":["[INTERNAL] \/home\/travis\/build\/PrestaShop\/autoupgrade\/tests\/ErrorHandlerTest.php line 51 - Exception: ERMAGHERD\n#0 [internal function]: ErrorHandlerTest->testCheckExceptionAndContent()\n#1 \/home\/travis\/build\/PrestaShop\/autoupgrade\/vendor\/phpunit\/phpunit\/src\/Framework\/TestCase.php(1062): ReflectionMethod->invokeArgs(Object(ErrorHandlerTest), Array)\n#2 \/home\/travis\/build\/PrestaShop\/autoupgrade\/vendor\/phpunit\/phpunit\/src\/Framework\/TestCase.php(913): PHPUnit_Framework_TestCase->runTest()\n#3 …
```
> Do not display exception when running unit tests

- classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php
The CLDR is being reworked on PrestaShop with https://github.com/PrestaShop/PrestaShop/pull/12999. Once merged, some classes will be removed.
This PR adds a check on the concerned class before calling them.
> Call CLDR update only if the class exists

- ajax-upgradetab.php
- ajax-upgradetabconfig.php
- classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php
- classes/ZipAction.php
PR content:
* When an ajax requests fails the security checks, we set its code as 401.
* Better retrieval of the `dir` parameter
* When extracting files from a zip file, report the concerned file in case of failure
* Split error messages when upgrading languages
> Improve report of errors and fix notices

- AdminSelfUpgrade.php
- classes/Parameters/UpgradeConfiguration.php
- classes/Parameters/UpgradeConfigurationStorage.php
- classes/TaskRunner/Upgrade/UpgradeComplete.php
- classes/UpgradeTools/FileFilter.php
Also, image backup is now by default
> Improve configuration getter for image backup

- classes/TaskRunner/Upgrade/AllUpgradeTasks.php
- classes/TaskRunner/Upgrade/UpgradeDb.php
- classes/TaskRunner/Upgrade/UpgradeFiles.php
- classes/UpgradeContainer.php
- classes/UpgradeTools/CacheCleaner.php
- classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php
- classes/UpgradeTools/CoreUpgrader/CoreUpgrader16.php
- classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php
- classes/UpgradeTools/FileFilter.php
- classes/UpgradeTools/SymfonyAdapter.php
- tests/UpgradeContainerTest.php
Allow var/cache:
* to be cleaned during upgrade process
* to be ignored when creating backups
Also, this PR moves the cache cleanup between the steps "Files upgrade" & "DB upgrade", right before the core initialization.
> Handle folder var/cache in module

- classes/Log/Logger.php
- classes/Log/LoggerInterface.php
- classes/LoggedEvent.php
- classes/LoggedEventIo.php
- classes/UpgradeTools/CacheCleaner.php
- classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php
- classes/UpgradeTools/SettingsFileWriter.php
- classes/UpgradeTools/Translation.php
- classes/Workspace.php
- classes/ZipAction.php
- composer.json
- composer.lock
Fixes `[INTERNAL] /var/www/html/var/cache/prod/classes.php line 9103 - Cannot redeclare class Psr\Log\LoggerInterface` while upgrading to PS 1.7.6.0
> Avoid conflit with Psr\Log\LoggerInterface when loading core

- classes/PrestashopConfiguration.php
settings.inc.php is still searched in 1.7 upgrade
cf https://github.com/PrestaShop/autoupgrade/issues/321
> Fix warning in 1.7 when settings file does not exist

- classes/TaskRunner/Upgrade/UpgradeModules.php
- classes/ZipAction.php
This PR removes the log "Extract using ZipArchive", which is now always true, and add details the path to the zipfile being modified to the logs. This provides additional details to the user about how the module works.
> Update logs around zip upgrade

- composer.json
Disabling the option `prepend-autoloader` will allow the PrestaShop autoloader to go first. Although it seems dangerous as the core is unstable during the upgrade, it seems to fix some issues like https://github.com/PrestaShop/PrestaShop/issues/13633
:warning: Run `composer install` after applying this PR
> Prepend and optimize autoloader

- AdminSelfUpgrade.php
- autoupgrade.php
- classes/Twig/Block/UpgradeChecklist.php
- classes/UpgradeSelfCheck.php
- css/styles.css
- js/dashboard.js
- upgrade/install-4-7-0.php
- upgrade/install-4-9-0.php
- views/templates/block/checklist.twig
- views/templates/hook/dashboard_zone_one.tpl
This PRs notifies when the running PHP server reached its end of life at 2 places, but the module remains compatible with PHP v5.6.
Not OK: ` The PHP version your server is running on is obsolete and needs to be upgraded. Learn more why or ignore.`
OK: `Your server is running on a supported PHP version.`
```
<head>PHP Version notice
<body>The PHP version your shop is running on is insecure.
It reached its end-of-life, which means it won't get security updates anymore and projects will stop supporting it.
Upgrading will keep your shop secured and performant.
<button>Learn more about PHP and upgrading
```
> Display a notice if PHP is below v7.1

- .travis.yml
- AdminSelfUpgrade.php
- Readme.md
- classes/Parameters/UpgradeConfigurationStorage.php
- classes/State.php
- classes/TaskRunner/Backup/AllBackupTasks.php
- classes/TaskRunner/Backup/Backup.php
- classes/TaskRunner/Backup/BackupComplete.php
- classes/TaskRunner/Backup/BackupDb.php
- classes/TaskRunner/Backup/BackupFiles.php
- classes/TaskRunner/Miscellaneous/UpdateConfig.php
- classes/TaskRunner/Upgrade/RemoveSamples.php
- classes/Twig/Form/BackupOptionsForm.php
- classes/UpgradePage.php
- classes/UpgradeTools/TaskRepository.php
- cli-backup.php
- js/upgrade.js
- views/templates/block/checklist.twig
Backup tasks have been removed from the upgrade process, as it can take a long time. Each backup must be triggered manually.
The current web interface does not allow to trigger the backup, because it is supposed to be completely reworked.
> Split upgrade & backup process

- classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php
SQL upgrade files can use DB_NAME placeholder
Which will be useful for 1.7.7.0 version (see SQL upgrade file)
Test: to validate this modification you will need to create a build based on this PR https://github.com/PrestaShop/PrestaShop/pull/16465 which uses the new feature (so you can validate 2 PRs at once, amazing!)
> SQL upgrade files can use DB_NAME placeholder

- upgrade/install-4.9.0.php
| Branch?       | develop
| Description?  | v4.9.0 upgrade filename was wrong, so it was probably ignored 🤔
| Fixed ticket? |  
| How to test?  | Please check that, following an upgrade from a version < 4.9.0 to a version > 4.9.0 autoupgrade module is correctly registered on hook `dashboardZoneOne` and set to top
> Fix v4.9.0 upgrade filename

- .travis.yml
| Description?  | Just realized https://github.com/PrestaShop/autoupgrade/pull/361 is probably useless. Because phpunit tests will be moved in GitHub Actions and phpstan tests and integration tests are run in a docker image so the PHP version used by Travis does not matter.
| Fixed ticket? | 
| How to test?  |
> Revert "Test upgrades for PS1.7 with php7.1"

- classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php
| Description?  | Because this module was checking the presence of a file instead of checking the version of PrestaShop, if that file was present, the module was calling a function from it that throw a exception in recent version of PrestaShop leading in a upgrade error. This PR fixes it by checking the PrestaShop version.
| How to test?  | Upgrade from PS < 1.7.6.0 to 1.7.7.0, no error should be displayed.
> Check for version instead of if file exists

- classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php
| Description?      | Please be specific when describing the PR. Every detail helps: What are you changing? Why?
| Fixed ticket?     | Partially PrestaShop/PrestaShop#22668
| How to test?      | Once https://github.com/PrestaShop/PrestaShop/pull/22682 is merged, try migrating from 1.6.1.24 to a build of PrestaShop containing #22682 **with `Use default theme` option selected** in the 1-click upgrade module. The process should complete without any error.
| Possible impacts? | /
> Clear cache before enabling theme

- autoupgrade.php
| Description?  | The method registerHookAndSetToTop must be public
| Type?         | bug fix 
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/22399
| How to test?  | Try to upgrade module from v4.8 to v4.9 (see ticket details)
When upgrading the module from version 4.8.0 through command line you should not have an error  In install-4.9.0.php line 32: Call to private method Autoupgrade::registerHookAndSetToTop() from context    ![image](https://user-images.githubusercontent.com/7163132/102023224-34791b80-3d8c-11eb-96fa-f1ec74e5133d.png) As the function is called in upgrade file it can not be private.
> Fix error with private method and upgrade

- .github/get_matrix.php
| Description?      | Now that autoupgrade results are pushed on the nightlyboard, these results were used in the get_matrix function leading to duplicate jobs. This PR fixes it
| How to test?      | `php .github/get_matrix.php` should return a json table with only 2 objects.
> Fix get_matrix returning the same value twice

- .github/action.yml
- .github/action_upgrade.sh
- .github/get_matrix.php
- .github/get_results.php
- .github/workflows/nigthly_upgrade.yml
- .github/workflows/upgrade.yml
- classes/TaskRunner/Miscellaneous/UpdateConfig.php
| Description?      | This PR aims to add nightly migration tests by adding 1.6.1.24 & 1.7.7.0 to the list of versions to migrate from. It also re-enable migration from 1.6.1.11 in the "classic" tests.
| Fixed ticket?     |
| How to test?      | CI should be green
> Add more nightly tests and re-enable 1.6 migration test

- classes/TaskRunner/Rollback/RestoreDb.php
| Description?  | Fix deletion of some tables by mistake
| BC breaks?    | Nope
| Deprecations? | Nope
| Fixed ticket? | /
| How to test?  | Backup, upgrade then restore, the customer data must remain in DB
> Avoid drop of some tables like guests

- classes/TaskRunner/Upgrade/BackupDb.php
| Description?      | Since MySQL 8.0, if there is a table with the name of the view you want to drop, you'll get an error. This PR fixes it by deleting the table before trying to delete the view.
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/24872
| How to test?      | Please see https://github.com/PrestaShop/PrestaShop/issues/24872
> Delete table before delete view

- .github/workflows/e2e_nightly_upgrade.yml
- tests/e2e/globals.js
- tests/e2e/scenarios/01_install.js
- tests/e2e/scenarios/02_upgrade.js
- tests/e2e/scripts/copy_reports.sh
| Description?      | Since E2E tests run only on the dev branch, we don't have real-time errors on upgrades. So adding run on the main branch
| How to test?      | no tests needed
> Run E2E tests on master 

- classes/Tools14.php
| Description?      | Fopen requires secong parameter for open mode
| How to test?      | CI green<br>If `allow_url_fopen` is set to false or 0 or Off in php.ini, curl will be used to download the PS binary, otherwise, fopen will be used. <br>To test this PR, use fopen
> Add second parameter for fopen in Tools14::copy

- .github/workflows/e2e_nightly_upgrade.yml
| Description?      | Update E2E tests to run on 1.7.7.8
| How to test?      | Nightly should test upgrade from 1.7.7.8
> Update E2E tests to run on 1.7.7.8

- .github/Dockerfile
- .github/action.yml
- .github/action_upgrade.sh
- .github/workflows/nigthly_upgrade.yml
- classes/TaskRunner/Upgrade/UpgradeModules.php
- classes/UpgradeTools/ModuleAdapter.php
- tests/phpstan/phpstan-PS-16.neon
- tests/phpstan/phpstan.neon
| Description?      | As there is no common compatible php version between PS 1.6 and develop, this PR aims to perform the upgrade in 2 steps (1.6 -> 1.7 with php 7.1 then 1.7 -> develop with php 7.2) so there is always a common compatible php version. 
| How to test?      | CI should be green
> Enable upgrades from 1.6 to develop

- views/templates/block/upgradeButtonBlock.twig
| Description?      | When we select the minor chanel there is a message that is no longer necessary.
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/26035
| How to test?      | Select minor chanel and check
> Remove useless message

- classes/TaskRunner/Miscellaneous/UpdateConfig.php
- classes/Twig/Block/UpgradeButtonBlock.php
- classes/UpgradeContainer.php
- classes/Upgrader.php
- js/upgrade.js
- tests/phpstan/Dockerfile
- views/templates/block/upgradeButtonBlock.twig
| Description?      | This PR aims to provide a way to use a local xml file containing the md5 sum of every files of the zip. This xml file is usually provided by an online API but when we use a local archive of a PrestaShop version that is not released yet, there was no easy way to do it.
| How to test?      | Try an upgrade from 1.6.1.24 to build of PrestaShop that is not released yet using the new "XML file to use:" field (xml files should be put in the same folder as the zip): <img width="559" alt="Capture d’écran 2021-12-06 à 17 10 51" …
> Add optional xml field for archive channel

- upgrade/sql/1.7.8.0.sql
- upgrade/sql/1.7.8.3.sql
| Description?      | "Error: invalid e-mail address" when opening modules page in debug mode after upgrade to 1.7.8
| Fixed ticket?     | Fixes PrestaShop/PrestaShop#26680
| How to test?      | Upgrade PrestaShop to 1.7.8 in debug mode and go to the module page
| Possible impacts? | no
> Add logs email receivers in configuration table

- upgrade/sql/1.7.8.4.sql
Fixes https://github.com/PrestaShop/PrestaShop/issues/27156 updating size to 80 chars for PREFIX_state.name field.
| Description?      | Updating PREFIX_State.name field to 80 chars according to PR https://github.com/PrestaShop/PrestaShop/pull/27162
| BC breaks?        | yes
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/27156.
| How to test?      | This PR should be approved at the same time as PR https://github.com/PrestaShop/PrestaShop/pull/27162 which changes the field size to 80 chars.
| Possible impacts? | None that I know of.
> Updated PREFIX_state.name field to 80 chars.

- upgrade/sql/8.0.0.sql
| Description?      | Add 410 http code to redirect_type column
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/27413
| How to test?      | See other PR in Core
> Add 410 http code to redirect_type column

- .github/workflows/php.yml
- classes/TaskRunner/Upgrade/UpgradeDb.php
- classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php
- classes/UpgradeTools/CoreUpgrader/CoreUpgrader80.php
- tests/phpstan/phpstan-1.6.1.18.neon
- tests/phpstan/phpstan-1.7.2.5.neon
- tests/phpstan/phpstan-1.7.3.4.neon
- tests/phpstan/phpstan-1.7.4.4.neon
- tests/phpstan/phpstan-1.7.5.1.neon
- tests/phpstan/phpstan-1.7.6.neon
- tests/phpstan/phpstan-1.7.7.neon
- tests/phpstan/phpstan-1.7.8.neon
| Description?      | Use GenerateThemeMailTemplatesCommand during upgrade instead of legacy removed Language::installEmailsLanguagePack function
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/26503
| How to test?      | PrestaShop/PrestaShop#27276 must be merged before. Build the module based on this branch Install it and try to upgrade to 8.0.0 (you will probably need to create a release from the most recent develop branch). You shouldn't have anymore error related to mail generation (there might be other errors down on the road but it's not the purpose of this PR)
| …
> Use GenerateThemeMailTemplatesCommand during upgrade

- classes/UpgradeSelfCheck.php
- tests/e2e/scenarios/02_upgrade.js
| Description?      | Since #440 has been merged, `ConfigurationTest::test_intl()` is called but this method was introduced in PrestaShop in 1.7.5.1 only. This PR aims to check if functions exists before calling them. It also fixes the nightly CI configuration check that is now 8 items long instead of 10. There's no need to put the store into maintenance mode as localhost is considered safe to upgrade. [This last configuration error](https://github.com/PrestaShop/autoupgrade/pull/445#issuecomment-1079197168) is also fixed.
| How to test?      | 1. From a PrestaShop 1.7.4.4, install …
> Handle PrestaShop versions before 1.7.5.1 + CI fix

- .github/workflows/e2e_nightly_upgrade.yml
- tests/e2e/.gitignore
- tests/e2e/configClassMap.js
- tests/e2e/globals.js
- tests/e2e/pages/BO/shopParameters/general/index.js
- tests/e2e/pages/BO/shopParameters/general/maintenance/index.js
- tests/e2e/scenarios/02_upgrade.js
| Description?      | Add pages to enable maintenance mode before upgrade
| How to test?      | Tested with workflow
> Add pages to enable maintenance mode before upgrade

- upgrade/sql/8.0.0.sql
| Description?      | Add hooks displayAdminThemesListAfter and displayModuleConfigureExtraButtons for autoupgrade of 8.0.0
| Fixed ticket?     | See https://github.com/PrestaShop/PrestaShop/pull/27469 and https://github.com/PrestaShop/PrestaShop/pull/27461
> Add hooks displayAdminThemesListAfter and displayModuleConfigureExtraButtons for 8.0.0

- .github/action.yml
- .github/workflows/nigthly_upgrade.yml
| Description?      | Since #450 the file `modulesToUpgrade.list` is deleted at the end of the upgrade process, there is then no need to manually delete it manually during the upgrade tests.
| How to test?      | Error before this PR: https://github.com/PrestaShop/autoupgrade/runs/6150038767?check_suite_focus=true#step:5:438<br>Error after this PR: https://github.com/atomiix/autoupgrade/runs/6155485959?check_suite_focus=true#step:5:941<br>The error left will be fixed in another PR
> File modulesToUpgrade.list doesn't need to be manually deleted anymore

- classes/Twig/Block/UpgradeButtonBlock.php
- classes/Upgrader.php
| Description?      | Since PHP 8.1, `version_compare()` cannot accept `null` as an argument. This PR fixes it by checking that the argument `version_num` is not null before using it in the `version_compare()` function.
| Fixed ticket?     | Fixes PrestaShop/PrestaShop#28631
| How to test?      | Please see PrestaShop/PrestaShop#28631
> Fix PHP 8.1 deprecated notice

- upgrade/sql/8.0.0.sql
| Description?      | These upgrade queries are related to this PR https://github.com/PrestaShop/PrestaShop/pull/26762 which adds a new column in product tables<br>In 178 the product table used the `unit_price_ratio` to save the unit price, so the actual value was not saved only the ratio instead. In 8.0.0 we now have a `unit_price` column which persists the actual value specified in the BO and used in the FO. But we kept the `unit_price_ratio` for backward compatibility for now.<br><br>This upgrade PR does to things:<br>- it adds the new column `unit_price` in the database<br>- it computes its value based on existing `unit_price_ratio` and `price` column
| Type?             | …
> Add SQL upgrade queries for new unit price column

- upgrade/sql/8.0.0.sql
| Description?      | Some configuration values were missing in sql. Refer to https://github.com/PrestaShop/PrestaShop/issues/29395
| Fixed ticket?     | https://github.com/PrestaShop/PrestaShop/issues/29395
| How to test?      | refer to https://github.com/PrestaShop/PrestaShop/issues/29395
> Instert configuration values for password policy

- .github/workflows/php.yml
- classes/UpgradeTools/CoreUpgrader/CoreUpgrader80.php
- classes/UpgradeTools/ModuleAdapter.php
- tests/phpstan/phpstan-1.6.1.18.neon
- tests/phpstan/phpstan-1.7.2.5.neon
- tests/phpstan/phpstan-1.7.3.4.neon
- tests/phpstan/phpstan-1.7.4.4.neon
- tests/phpstan/phpstan-1.7.5.1.neon
- tests/phpstan/phpstan-1.7.6.neon
- tests/phpstan/phpstan-1.7.7.neon
- tests/phpstan/phpstan-1.7.8.neon
- tests/phpstan/phpstan-8.0-beta.1.neon
- tests/phpstan/phpstan-8.0.0-beta.1.neon
- tests/phpstan/phpstan-latest.neon
- tests/phpstan/phpstan.neon
- upgrade/php/deactivate_custom_modules.php
| Description?      | when upgrading to PS8.0 or later, we want non native modules to be disabled
| Fixed ticket?     | Fixes [#25649](https://github.com/PrestaShop/PrestaShop/issues/25649)
| How to test?      | 1/ Install a non native module (for example a prestashop example module) <br> 2/ Install autoupgrade module from this PR <br> 3/ Remove problematic modules (welcome mbo metrics facebook psxmarketingwithgoogle) <br> 4/ Make a release from prestashop 8.0.x [with this PR](https://github.com/PrestaShop/PrestaShop/pull/29469) <br> 4/Upgrade your  shop via local archive with your generated release …
> Disable non native modules on PS8.0 and onward

- upgrade/sql/1.7.8.8.sql
| Description?      | Please be specific when describing the PR. Every detail helps: What are you changing? Why?
| How to test?      | After the update to 1.7.8.8, the table `ps_configuration` should not contain an entry with the name `PS_SMARTY_CACHING_TYPE`.
> Remove PS_SMARTY_CACHING_TYPE configuration in 1.7.8.8

- upgrade/php/ps_remove_controller_tab.php
- upgrade/sql/8.0.0.sql
| Description?      | Theme and module catalog tab links have been removed in 8.0.0, autoupgrade should take that into account
| Fixed ticket?     | Fixes [#29394](https://github.com/PrestaShop/PrestaShop/issues/29394)
| How to test?      | See how to test in issue [#29394](https://github.com/PrestaShop/PrestaShop/issues/29394)
> Add method to recursively remove tabs, and use it for PS8 upgrade

- classes/TaskRunner/Upgrade/UpgradeDb.php
- js/upgrade.js
This PR fixes CoreUpgrader file
If you want to update to version 8.0, the core upgrader uses the CoreUpgrader17 instead of CoreUpgrader8.
(the selected core upgrader depends on the targeted version and not from the source version) 
Fixes https://github.com/PrestaShop/PrestaShop/issues/29248
1/ In the autoupgrade form, choose upgrade via local archive
2/ In the field for the upgrade version, you should only be able to enter versions with a patch precision, example:
- 1.7.7.8
- 8.0.0
- 1.6.1.24
Examples of wrong versions (you will get an error message):
- 1.7.2
- 8.0
- 8.0.0.0
(Notice how for PS 8 and above, the version is made of 3 numbers, while it's 4 numbers for older versions)
> Fix version compare check to use CoreUpgrader 8 with 8.0 version

- views/templates/block/activityLog.twig
- views/templates/block/channelInfo.twig
- views/templates/block/checklist.twig
- views/templates/block/rollbackForm.twig
- views/templates/block/upgradeButtonBlock.twig
- views/templates/block/versionComparison.twig
- views/templates/main.twig
| Description?      | Add domain in all trans calls in twig templates, the `Modules.Autoupgrade.Admin` was missing thus, the wordings could not be scanned and be included in the PrestaShop catalog
| BC breaks?        | yes
| How to test?      | Check that the module is still usable, but we can't check if the translation works fine since the catalog has not been updated yet
| Possible impacts? | Previously the module relied on internal PHP trad, now it will use the catalog from the core So for a while, the translations may not be available anymore
> Add domain in all trans calls in twig templates

- upgrade/sql/8.0.0.sql
| Description?      | Remove module catalog tab even when MBO module is not installed
| Fixed ticket?     | Fixes [#29858](https://github.com/PrestaShop/PrestaShop/issues/29858)
| How to test?      | 1/ Install prestashop 1.7.8.7<br>2/ do not uninstall mbo module<br>3/Install autoupgrade module<br>4/Make sure the "disable non-native modules" option is activated<br>5/ Upgrade to PrestaShop 8<br>6/ After upgrade, check that the module catalog link has been removed in the left menu
> Remove module catalog tab even when MBO module is not installed

- upgrade/sql/8.0.0.sql
| Description?      | BO & FO - The default Carrier is wrong after an upgrade from 1.7 to 8.0.0 if carrier name is set to 0 in db
| Fixed ticket?     | Fixes PrestaShop/PrestaShop#29637
| How to test?      | See https://github.com/PrestaShop/PrestaShop/issues/29637
> Don't use 0 value for carrier name

- upgrade/sql/8.1.0.sql
| Description?      | Removed `US/Pacific New` from timezone list
| Fixed ticket?     | Fixes PrestaShop/PrestaShop#14411
| How to test?      | - Define the configuration value for `PS_TIMEZONE` to `US/Pacific-New`<br/>- Upgrade to version 8.1.0<br/>- The configuration value for `PS_TIMEZONE` should be `US/Pacific`
| Possible impacts? | N/A
> Removed `US/Pacific New` from timezone list

- upgrade/php/editorial_update.php
| Description?      | Fix error validator - "Creating an already existing SQL table will crash the shop. Add "IF NOT EXISTS" after "CREATE TABLE""
| Fixed ticket?     | NO
| How to test?      | See how to test
| Possible impacts? | no
**How to test**
- Connect to https://validator.prestashop.com/
- Upload the zip of the autoupgrade
- Click on process validation
- In the Errors column, Check that the error `Creating an already existing SQL table will crash the shop. Add "IF NOT EXISTS" after "CREATE TABLE"` doesn't exist
**Before**
**After**
> Fix error validator - "Create table SQL"

- upgrade/sql/1.7.8.8.sql
| Description?      | Since the translation system changed in 1.7.8, translating the classic theme needs to have the value `null` in the `theme` column in `ps_translation` instead if having `classic`.
| Fixed ticket?     | Fixes PrestaShop/PrestaShop#29164
| How to test?      | Please see PrestaShop/PrestaShop#29164
> Set translation theme to null is it was classic

- .github/workflows/e2e_nightly_upgrade.yml
| Description?      | Disable e2e tests cron to not push on nightly
| How to test?      | N/A
| Possible impacts? | N/A
> Disable e2e tests cron to not push on nightly

- .github/workflows/php.yml
- classes/TaskRunner/Upgrade/UpgradeDb.php
- classes/UpgradeTools/CoreUpgrader/CoreUpgrader81.php
| Description?      | Since PrestaShop/PrestaShop#29931, 2 new keys are needed in the file `app/config/parameters.php`. This PR aims to add them during the upgrade.
| How to test?      | Try to upgrade from 1.7.8.x/8.0.0 to 8.1.0 (develop). The upgrade should run without error.
> Add missing keys for 8.1.0

- upgrade/sql/8.1.0.sql
| Description?      | There is no possibility to add something (message) on address step of checkout. So we suggest please add a display hook in the address step also just like other checkout steps.
| Type?             |  new feature 
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/30666
| How to test?      | Please indicate how to best verify that this PR is correct.
> Add a display hook in the address step

- upgrade/php/ps_810_add_product_attribute_lang_data.php
- upgrade/sql/8.1.0.sql
| Description?      | Autoupgrade PR for https://github.com/PrestaShop/PrestaShop/pull/29411
| How to test?      | Have some products with combinations. Do upgrade to 8.1 and check that new table `ps_product_attribute_lang` with data is created. Try to edit some combinations, should work fine.
| Possible impacts? | no
> Add and fill combination lang table

- upgrade/sql/8.1.0.sql
| Description?      | Autoupgrade PR for https://github.com/PrestaShop/PrestaShop/pull/29720
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/pull/29720
- Install Prestashop 8
- Check that some or all products have `redirect_type` in `ps_product` table `404`.
- Do upgrade to 8.1.
- Go check `ps_product` again and see that these products changed `redirect_type` to `default`.
> Add config and data for discontinuted products

- upgrade/sql/8.1.0.sql
| Description?      | Change limit of filed value on ps_customized_data so that it can accepts more than 255 characters
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/27579
| Sponsor company   |
1) Install a shop with version older than develop
2) upload module autoupgrade with this PR merged
3) Use autoupgrade to upgrade to develop
4) Install classic theme with this https://github.com/PrestaShop/classic-theme/pull/100 merged (to be able to add more than 255 characters. You can instead remove the 255 characters constraint directly in the element …
> Change limit of filed value on ps_customized_data so that it can accepts more than 255 characters

- classes/UpgradeSelfCheck.php
| Description?      | The core PHP session test of PrestaShop checks if the sessions directory is writable, which does not always work as expected. Combined with an open_basedir configured without the session.save_path, PHP sessions are still working as intended, but the test_sessions function fails. In such a case, the One Click Upgrade module will fail checking its prerequisites in an attempt to make an upgrade. This fixes the issue on all old cores, because it implements the check inside the module.
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/30658
| Sponsor company   | …
> Fix session test

- autoupgrade.php
Remove copy of unused logo
| Description?      | This will fix issue 31387 where an removed and unused gif was attempted to be copied, and thus preventing install of the module.
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/31387
| Sponsor company   | Prestaworks AB
| How to test?      | Install autoupgrade module (Dev version)
> Remove attempt to copy removed icon

- upgrade/sql/8.1.0.sql
| Description?      | Add the option PS_MAINTENANCE_ALLOW_ADMINS (enabled by default)
| Fixed ticket?     | Related PR https://github.com/PrestaShop/PrestaShop/pull/30169
| How to test     | Install v8. Run `SELECT * FROM ps_configuration WHERE name = 'PS_MAINTENANCE_ALLOW_ADMINS';`, finds nothing. Upgrade to v9. Run query again. Finds the configuration entry.
> Add PS_MAINTENANCE_ALLOW_ADMINS to the configuration table

- classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php
- upgrade/php/install_ps_distributionapiclient.php
- upgrade/sql/8.0.0.sql
| Description?      | Install ps_distributionapiclient after upgrade >= 8.0 to purpose modules updates without install manually ps_distributionapiclient module
| Sponsor company   | Prestashop SA
| How to test?      | Upgrade PS 1.7.8.8 to 8.0 and check if module ps_distributionapiclient is installed and if there is updates available in modules list
> Install ps_distributionapiclient after upgrade >= 8.0

- upgrade/sql/8.1.0.sql
| Description?      | In the PR https://github.com/PrestaShop/PrestaShop/pull/28640 a bug was detected related to employee with long name or firstname, it cause a bug while creating a stock movement because the `stock_mvt` structure can't handle such long values
| How to test?      | When upgrading from version prior ao 8.0.0 check the DB structure, in the `stock_mvt` table the columns `employee_lastname` and `employee_lastname` used to be `VARCHAR(32)` now they should be `VARCHAR(255)` to match the length from the employee table
| Possible impacts? | ~
> Update stock movement DB employee fields

- upgrade/sql/8.1.0.sql
| Description?      | Adds new image formats configuration and feature flag
| Fixed ticket?     | https://github.com/PrestaShop/PrestaShop/issues/31663
| How to test?      |  1/ Upgrade a shop to 8.1<br> 2/ Check that the "multiple image formats" feature flag is present, and activate it<br>3/ Go in settings > image, and check that you have new image format selection checkboxes
> Add new image feature flag and configuration values

- upgrade/sql/8.1.0.sql
| Description?      | Changing the stock_mvt tables quantity input to unsigned. It is always positive number and by doing this we can insert twice as big int and after this [PR](https://github.com/PrestaShop/PrestaShop/pull/30592) we need that.
| Type?             | improvement 
| Fixed ticket?     | Fixes [27313](https://github.com/PrestaShop/PrestaShop/issues/27313).
| How to test?      | Run upgrade and check if table stock_mvt had the column physical_quantity changed to UNSIGNED.<br>IMPORTANT NOTE: since the modified table is related to a Doctrine entity it's possible that the DB is already automatically updated via the doctrine …
> Added stock mvt upgrade

- classes/UpgradePage.php
- js/upgrade.js
- views/templates/block/upgradeButtonBlock.twig
| Description?      | Requires the XML file when upgrading with archive
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/29932.
| How to test?      | Follow the steps in the issue
| Possible impacts? | Autoupgrading with an archive
> Requires the XML file when upgrading with archive

- upgrade/php/add_hook.php
| Description?      | This helper makes adding hooks even easier and eases the process of review of such PRs
| Fixed ticket?     | n/a
| Sponsor company   | Mr Podemsky Corp
| How to test?      | Install 8.0.1, use helper in 8.0.2 upgrade script and upgrade, and see if a new hook exists. Developer feature, developer QA probably.
How to use it?
`/* PHP:add_hook('mySuperAwesomeHook', 'Super awesome hook', 'This is yet another awesome hook in PrestaShop'); */;`
> Helper for adding hooks in upgrade scripts

- .github/workflows/php.yml
- composer.json
- composer.lock
- upgrade/php/ps_810_update_product_page_feature_flags.php
- upgrade/sql/8.1.0.sql
| Description?      | Update product page feature flag values and adapt the current state based on existing values
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/31381
| Sponsor company   | ~
| How to test?      | - When upgrading from 8.0.0 and product page V2 is enabled for single shop after the upgrade the product page should be enabled<br>- When upgrading from 8.0.0 and product page V2 is enabled for multi shop after the upgrade the product page should be enabled<br>- When upgrading from 8.0.0 and product page V2 is NOT enabled for single shop nor multi shop after the …
> Update product page feature flag values

- .github/Dockerfile
- .github/Dockerfile-7.1
| Description?      | After the prestashop.com rebranding, some links were broken. 
| Type?             | bug fix 
This PR will work only with PrestaShop >= 1.5.6.0.
> Fixed URL to download PrestaShop releases

- classes/UpgradeTools/ModuleAdapter.php
- tests/phpstan/phpstan-1.6.1.18.neon
- tests/phpstan/phpstan-1.7.2.5.neon
- tests/phpstan/phpstan-1.7.3.4.neon
- tests/phpstan/phpstan-1.7.4.4.neon
| Description?      | Use interface instant of implementation for get command-bus return. Also TacticianCommandBusAdapter no longer exist in 9.0.0
> Use interface instant of implementation

- upgrade/sql/9.0.0.sql
| Description?      | Add `type` column in `feature_flag` table needed for https://github.com/PrestaShop/PrestaShop/pull/32923
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/32698
> Add type in feature_flag table

- upgrade/sql/8.1.0.sql
- upgrade/sql/9.0.0.sql
| Description?      | See below
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/33489
| How to test?      | Upgrade 8.0 to 8.1 and check that ps_customized_data value stayed the same and is NOT 1024.
PR was merged to v9 - https://github.com/PrestaShop/PrestaShop/pull/31109
Autoupgrade was merged to 8.1 - https://github.com/PrestaShop/autoupgrade/pull/556
> Move script to proper location

- classes/TaskRunner/Upgrade/UpgradeDb.php
- classes/UpgradeContainer.php
- classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php
| Description?      | Resets opcache when cleaning file cache.
| Fixed ticket?     | Does not fix any specific issue, but there may be many issues caused by this we did not even know we fixed. :-)
| How to test?      | Follow steps in issue.
> Clean opcache when cleaning cache

- upgrade/php/ps_811_update_redirect_type.php
- upgrade/sql/8.1.0.sql
- upgrade/sql/8.1.1.sql
| Description?      | I forgot to update product redirect_type and QA did not catch that it doesn't work on upgraded 8.1.0 installs. This adds the missing queries for people upgrading to 8.1.0 and it adds a script that will fix it for people who updated to 8.1.0 already.
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/33488
| How to test?      | Upgrade 8.0 to 8.1, open phpmyadmin, check structure of ps_product table and see that column redirect_type has is `ENUM('','404','410','301-product','302-product','301-category','302-category','200-displayed','404 …
> Fix product redirect_type

- classes/TaskRunner/Upgrade/UpgradeModules.php
Hello,
I'm the contributor for the module "Stripejs" payment module and I've got lots of complains that the module does gets deleted while upgrading Prestashop. So I opened an issue to fix it but nothing was done after long time. https://github.com/PrestaShop/PrestaShop/issues/27561 So I decided to do it myself.
The code which I removed from this autopgrade module, is responsible to delete my module during the upgrade. 
Please consider this change at high priority because thousands of customers are constantly facing this serious issue. 
Best Regards,
Sitender
| Description?      | Bug fixed to stop deleting a popular Stripe payment module during PrestaShop …
> Avoid deleting a popular payment module "stripejs"

- js/upgrade.js
| Description?      | Version validation regex didn't take PS 9 into account
| Type?             | bug fix 
| Fixed ticket?     | Partially Fixes https://github.com/PrestaShop/PrestaShop/issues/33578
| How to test?      | See https://github.com/PrestaShop/PrestaShop/issues/33578
> Update version regex in JavaScript

- classes/UpgradeTools/FileFilter.php
| Description?      | Prevent existing overrides from being wiped during upgrade to PS8
| BC breaks?        | n/a
| Deprecations?     | n/a
| Fixed ticket?     | Fixes #33634  ( https://github.com/PrestaShop/PrestaShop/issues/33634 )
| How to test?      | Upgrade from PS 1.7.x to PS 8.x having some overrides - compare override folder before / after this PR
> Fix for #33634  - Prevent overrides being wiped during upgrade to PS8

- classes/TaskRunner/Upgrade/UpgradeModules.php
- classes/UpgradeTools/ModuleAdapter.php
| Description?      | Fix local module upgrade mechanism (and improve performance by only checking if the zip exist for modules we want to upgrade locally instead of checking the existence of a zip for all modules that will be upgraded)
| How to test?      | Put the zip of a module in admin/autoupgrade/modules, it should be of a version superior to the version currently installed. Do a prestashop upgrade, check that the module has been upgraded according to your zip
> fix local module upgrade

- .github/workflows/php.yml
- autoupgrade.php
- classes/UpgradeSelfCheck.php
- classes/Upgrader.php
- config.xml
| Description?      | Disable 'verify if module is latest' for shops under 1.7.0.0 for 4.14.x and bump version to 4.14.3
| How to test?      | See below
The upgrade module has a feature where it checks whether there is a more recent version of itself and if it does, it tells the user "please use the latest version, you are using an outdated version".
Currently if someone installs the module 4.14.2 on a shop, the module will detect there is a 4.16.3 version and says to user "please don't use me! use the latest 4.16.3 version instead!"
Consequently this PR …
> Disable 'verify if module is latest' for shops under 1.7.0.0 for 4.14.x and bump version to 4.14.3

- classes/UpgradeSelfCheck.php
| Description?      | See below
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/33886
| How to test?      | See ticket
When the Configuration page of the module is opened, the checklist is being verified. Function [UpgradeSelfCheck::checkKeyGeneration()](https://github.com/PrestaShop/autoupgrade/blob/dev/classes/UpgradeSelfCheck.php#L527) is called but at this moment `$this->upgrader->version_num` is NULL so the use of version_compare [triggers a warning](https://github.com/PrestaShop/PrestaShop/issues/33886).
At the beginning I was worried about …
> Do not check version if not provided

- upgrade/php/drop_column_if_exists.php
- upgrade/sql/1.7.7.0.sql
- upgrade/sql/1.7.8.0.sql
- upgrade/sql/8.0.0.sql
- upgrade/sql/8.1.0.sql
- upgrade/sql/8.1.2.sql
| Description?      | Fixes some database incosistencies on upgraded installs found in https://github.com/PrestaShop/PrestaShop/issues/33483. The differences do not necessarily mean something doesn't work, but removes the chance of biting us back with it. I fixed the things for both the original upgrade scripts AND 8.1.2, so we fix users that already upgraded.
| Fixed ticket?     | Fixes #https://github.com/PrestaShop/PrestaShop/issues/33483 partially
| How to test?      | Tests green + run the queries in 8.1.2.sql manually. Make sure to put `SET SESSION sql_mode='';` to the …
> Fix upgrade inconsistencies

- upgrade/sql/8.1.2.sql
- upgrade/sql/8.1.3.sql
| Description?      | Move fixes from https://github.com/PrestaShop/autoupgrade/pull/631 to 8.1.3.
| Type?             | 
| How to test?      | Already tested.
> Move fixes to 8.1.3 because the module was not released in time

- classes/ZipAction.php
| Description?      | See below
| How to test?      | Make an upgrade with given zip file on php8.1 installation
https://github.com/PrestaShop/autoupgrade/assets/7426640/9c5e13d6-fd36-4db6-8442-69244f31cd20
https://github.com/PrestaShop/autoupgrade/assets/7426640/72b97a04-a1fc-433d-8f31-af7a968f2ad0
The definition of ZipArchive::open changed between php 7 and php8
Passing null as 2nd parameter results on a Warning
PHP 7 => https://durak.org/sean/pubs/software/php-7.4.3/ziparchive.open.html
PHP 8 => https://www.php.net/manual/en/ziparchive.open.php
> Avoid warning for passing null as 2nd parameter of ZipArchive::open

- upgrade/sql/8.1.3.sql
| Description?      |  This PR is linked to PR [34242](https://github.com/PrestaShop/PrestaShop/pull/34242). It just update the PREFIX_customer.ape field from varchar(5) to varchar(6) to match all french APE code formats. I hope I haven't forgotten anything.
| Type?             |  improvement 
| Fixed ticket?     | Fixes for PR [34242](https://github.com/PrestaShop/PrestaShop/pull/34242), Fixes for issue [34216](https://github.com/PrestaShop/PrestaShop/discussions/34216)
| Sponsor company   | coquille.fr
| How to test?      | The ape field in  PREFIX_customer table should be varchar(6) after upgrade.
> Change the APE field validation to match all formats

- upgrade/sql/8.1.3.sql
| Description?      | Tooltip say "The minimum quantity required to buy this product (set to 1 to disable this feature)". So minimal_quantity should be 1 at least, not 0! Related to PR: https://github.com/PrestaShop/PrestaShop/pull/34537
| Fixed ticket?     | https://github.com/PrestaShop/PrestaShop/issues/18850
| Sponsor company   | https://www.openservis.cz/
> Minimal_quantity should be 1 at least, not 0!

- classes/ZipAction.php
| Description?      | When backup zip file closing fails, show which zip file was trying to be closed
| How to test?      | try to fail zip close to see the new message. <br />Before it was just `ERROR - Could not close the Zip file properly. Check you are allowed to write on the disk and there is available space on it.` <br />now it is `ERROR - Could not close the Zip file: /path/to/admin-dev/autoupgrade/backup/auto-backupfiles_V8.0.5_20231110-142932-5b1cebf4.zip properly. Check you are allowed to write on the disk and there is available space on it.`
> Show which file was trying to be closed when error on close

- classes/TaskRunner/Miscellaneous/CompareReleases.php
- classes/TaskRunner/Upgrade/UpgradeFiles.php
| Description?      | Solves a problem of some files not being deleted during upgrade. The common culprit was that these files had `/admin` in their paths.
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/34385 (partially, don't close)
| How to test?      | Upgrade from 1.7.6.9 to 8.1.2 and check that these files from the issue are gone.
- During my findings like in https://github.com/PrestaShop/autoupgrade/pull/651, I got to the step where it builds a list of files to get removed. It builds this list by comparing current version XML to a XML of the …
> Fix some files not being deleted

- upgrade/sql/8.0.0.sql
| Description?      | The script doesn't fill new session columns with data, resulting in an error sometimes. This fills it.
| Fixed ticket?     | Fixes #https://github.com/PrestaShop/autoupgrade/pull/652#issuecomment-1824717816
| How to test?      | Upgrade from 1.7.6.9 to 8.1.2, directly after upgrade, open phpmyadmin and check that there won't be an empty `date_add` and `date_upd` in `ps_employee_session`.
> Fill sessions with data after adding the column

- classes/PrestashopConfiguration.php
| Description?      | Get PrestaShop 8.1 version
| Sponsor company   | WEB AREA
| How to test?      | on PrestaShop 8.1
On PrestaShop 8.1 the version number has been moved to `/src/Core/Version.php`
See https://github.com/PrestaShop/PrestaShop/blob/8.1.x/src/Core/Version.php#L35
> Fix getPrestaShopVersion on 8.1

- classes/UpgradeTools/ModuleAdapter.php
| Description?      | Fix infinite loop after upgrade with local module zip
| Type?             | bug fix 
| Fixed ticket?     | https://github.com/PrestaShop/PrestaShop/issues/33866
> Fix infinite loop after upgrade with local module zip

- upgrade/sql/9.0.0.sql
| Description?      | Implements required database changes for recent 9.0.0 PRs.
| How to test?      | Run upgrade from 8.1.x to develop and check if it ran correctly. I ran everything in database admin and works correctly.
- https://github.com/PrestaShop/PrestaShop/pull/33363
- https://github.com/PrestaShop/PrestaShop/pull/33232
- https://github.com/PrestaShop/PrestaShop/pull/31151
- https://github.com/PrestaShop/PrestaShop/pull/33158
> Adapt upgraded installs to recent changes

- classes/UpgradeTools/Translation.php
| Description?      | Check if function get_magic_quotes_gpc() exists before use it. This function was DEPRECATED in PHP 7.4 and REMOVED in PHP 8.0
| Deprecations?     | yes
| Fixed ticket?     | Fixes #{[Prestashop/Prestashop#34988](https://github.com/PrestaShop/PrestaShop/issues/34988)}
| How to test?      | Run upgrade and check if it ran correctly
--
> Check if function get_magic_quotes_gpc() exists before use it

- upgrade/php/add_hook.php
- upgrade/sql/1.7.1.0.sql
- upgrade/sql/1.7.2.0.sql
- upgrade/sql/1.7.3.0.sql
- upgrade/sql/1.7.4.0.sql
- upgrade/sql/1.7.6.0.sql
- upgrade/sql/1.7.7.0.sql
- upgrade/sql/1.7.7.2.sql
- upgrade/sql/1.7.8.0.sql
- upgrade/sql/8.0.0.sql
- upgrade/sql/8.1.0.sql
- upgrade/sql/8.1.2.sql
- upgrade/sql/8.1.5.sql
- upgrade/sql/9.0.0.sql
| Description?      | Improves inserting of hooks into database during update. More info below.
- Right now, if an hook exists in a database via an automatic creation, it has no title and description.
- When you upgrade, it runs `INSERT IGNORE`, which doesn't result in an error, but it just doesn't do anything.
- Much better solution is to update the key if found and not use `IGNORE`.
- Yes, it's safe. UNIQUE KEY `hook_name` (`name`) exists in 1.6, maybe even sooner.
> Update hooks when they already exist

- upgrade/sql/9.0.0.sql
| Description?      | Set authorization_server feature true by default
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/34852
| How to test?      |after an upgrade to v9, ensure the authorization_server feature flag is true by default
> Set authorization_server feature flag true by default

- upgrade/sql/9.0.0.sql
| Description?      |Add category redirect columns
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/35500
| How to test?      | after an upgrade to v9, ensure the addition of new column `redirect_type` and `id_type_redirected` in the `PREFIX_category` table. Also check that the root category is in `redirect_type` 404
> Add category redirect columns

- upgrade/sql/9.0.0.sql
| Description?      | delete the obsolete PS_SSL_ENABLED_EVERYWHERE config
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/35487
| How to test?      | after an upgrade to v9, PS_SSL_ENABLED_EVERYWHERE is non longer present in configuration table
> Delete the obsolete PS_SSL_ENABLED_EVERYWHERE config

- autoupgrade.php
| Description?      | Fix tab visibility on PrestaShop 9
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/35726
| How to test?      | You can try to install the module on V8 or V9 all run as expected.
> Fix tab visibility on PrestaShop 9

- .github/action.yml
- .github/workflows/upgrade.yml
- classes/UpgradeTools/SymfonyAdapter.php
| Description?      | If you try upgrading from 1.7.1.0 to a version below 1.7.3.0, you get an error about AppKernel because this class is not present in the core autoload classmap. This PR adds: <ul><li>A safety net while loading AppKernel</li><li>Expands the tested versions of PrestaShop in CI,</li><li>Improved the readability of the base version running the shop in CI.</li></ul>
| Fixed ticket?     | NA
| How to test?      | Check if CI is green. To check the fix, try upgrading a PrestaShop 1.7.1.0 to 1.7.2.0.
> Add a failsafe require and add first working version of 1.7 in automatic tests

- upgrade/sql/9.0.0.sql
| Description?      | While upgrading to PrestaShop v9, remove tabs who lost their parent relation with the previous row deletion. this cleans the table and fixes an issue reported while opening the Stock page.
| Deprecations?     |Nope
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/35879
| Sponsor company   | PrestaShopCorp
| How to test?      | Upgrade from PS 8 to 9, then open the Stock page. It should load without error.
> Remove orphan tabs following deletion of old controllers

- classes/TaskRunner/Miscellaneous/CheckFilesVersion.php
- classes/TaskRunner/Miscellaneous/CompareReleases.php
- classes/UpgradeContainer.php
- classes/UpgradeTools/FileFilter.php
- classes/Upgrader.php
- classes/Xml/ChecksumCompare.php
- classes/Xml/FileLoader.php
- tests/unit/Xml/ChecksumCompareTest.php
| Description?      | This fixes an issue where modules files are unexpectly removed. It plugs XML diff to the method removing files to ignore, so the same rules during the copy of files are applied. <br><br>This also changes the way native modules are ignored. If one of them has never been modified (meaning their composer is still the one provided by the core), its content will be upgraded during the process.
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/36184
| How to test?      | * Basic upgrades from 8.1.0 to 8.1.6 must upgrade …
> Align ignoring rules between copy and deletion of files + ignore native module only if they have they vendor/ folder

- upgrade/sql/1.7.1.0.sql
- upgrade/sql/1.7.7.0.sql
- upgrade/sql/8.0.0.sql
| Description?      | Various SQL fix
| How to test?      | No SQL errors when we upgrade from 1.7.0.1 to 1.7.1.0 - No SQL errors when we upgrade from 1.7.8.11 to 8.0.0
> Various SQL fix

- autoupgrade.php
- config.xml
- upgrade/install-5.0.3.php
This PR is a cherry pick of https://github.com/PrestaShop/autoupgrade/pull/716 for the `dev` targeting versions 6+ of the module
| Description?      | When upgrading the module to 5.0.2, the old controller we removed on Git is not deleted on the shop. It remains called first by the shop, and because it does not have some the changes on how to instanciate UpgradeSelfCheck.
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/36317, Fixes https://github.com/PrestaShop/PrestaShop/issues/36330
| Sponsor company   | PrestaShopCorp
| How to test?      | ~Upgrade from 5.0.1 to 5.0.3, …
> Cherry pick: Remove old controller AdminSelfUpgrade.php manually

- classes/Parameters/UpgradeConfigurationStorage.php
- classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php
- classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php
- classes/UpgradeTools/ThemeAdapter.php
| Description?      | The pages in RTL languages are not displayed properly after an upgrade, this PR aims to make sure the generation is properly triggered.
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/29918, Fixes https://github.com/PrestaShop/PrestaShop/issues/29916, Fixes https://github.com/PrestaShop/PrestaShop/issues/27470
| How to test?      | Install PrestaShop on 1.7 with the Arabic language and the country Saudi Arabia. After upgrading the shop, the pages on the BO + FO must be the same as on a freshly installed shop.
> Improve regeneration of RTL files during upgrade

- classes/Log/LegacyLogger.php
- classes/UpgradeContainer.php
- tests/unit/Log/LegacyLoggerTest.php
| Description?      | In order to make sharing of upgrade logs safer for merchants, we sanitize some critical details before inserting in the logs. This starts with the name of the admin folder. Logs shown in CLI are not impacted.
| How to test?      | Admin folder is not anymore written in the file `log.txt` and on the logs displayed on the page.
> Sanitize sensitive data (admin folder) from logs

- classes/UpgradeSelfCheck.php
| Description?      | Add condition when version_num is null for compute PHP compatibility range
| How to test?      | Select "local archive" channel, save without selected files
> Add condition when version_num is null for compute PHP compatibility range

- .github/workflows/extract-translations.yml
| Description?      | It is currently difficult to update the translations. To do this, you must go to the BO of a shop containing the module in order to export the translations and then retrieve the file to place in our module. This PR is used to introduce an automatic export of translations from the CI.
| How to test?      | Just push something on dev branch with new translations inside files (like twig or php). You can see a new PR apear to add this translations.
> feat: start creating CI for extract translation

- .github/workflows/ui-test.yml
| Description?      | UI tests - Add PS versions from 8.0.0 ~ 8.1.7 (Minor) - PHP 7.2~ 8.1
| Sponsor company   | @PrestaShopCorps
| How to test?      | CI is :green_apple:
> UI tests - Add PS versions from 8.0.0 ~ 8.1.7 (Minor) - PHP 7.2~ 8.1

- classes/ChannelInfo.php
- classes/TaskRunner/Miscellaneous/CompareReleases.php
- classes/TaskRunner/Upgrade/Download.php
- classes/TaskRunner/Upgrade/UpgradeNow.php
- classes/UpgradeContainer.php
- classes/UpgradeSelfCheck.php
- classes/VersionUtils.php
- tests/unit/VersionUtilsTest.php
| Description?      | When we switched to major versions with a single level of number, we did not update the way they are managed from the channel.xml file. As a result, we had to specify all minor versions instead of majors only. This PR fixes the management of major versions from PS 8.
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/36430
| Sponsor company   | Your company or customer's name goes here (if applicable).
| How to test?      | When running a shop on PS 8.0, the minor channel should propose upgrades to PS 8.1.7
> Fix minor channel on PS 8 and above

- controllers/admin/AdminSelfUpgradeController.php
| Description?      | Fix undefined method 'addPath' in TwigLoader
| How to test?      | In Prestashop 1.7.3.0 with php version < 7.1, install module with marketplace, replace the content with this PR and test configuration page. An alert should be present information that the PHP version is not compatible
> Fix undefined method 'addPath' in TwigLoader

- classes/UpgradeTools/Translator.php
| Description?      | The auto export translation change XLF files structure we have to update the translator class to match it.
| Fixed ticket?     | --
| How to test?      | See if we got translations in Czechia or French (not all translations in French just somes)
> fix: translator to match to xlf format files

- js/sentry.js
| Description?      | The sentry logs were empty.
| How to test?      | Simulate an error. The sentry label is no longer empty when sending the error
> Fix sentry logs

- .github/workflows/ui-test.yml
| Description?      | When a pull-request in opened with another branch of this repository as Head, some workflows are executed several times (pull-request and push). The UI tests can take a lot of time, so let's run it only one time.<br/>The main concerned pull-requests are related to translations (i.e https://github.com/PrestaShop/autoupgrade/pull/787).
| How to test?      | Nothing change for pull-requests, the UI tests remain executed.
> Avoid UI tests to be run 2 times on local branches with PRs

- classes/ErrorHandler.php
- classes/Exceptions/UpgradeException.php
- classes/Task/Upgrade/UpgradeModules.php
- classes/UpgradeTools/ModuleAdapter.php
- cli-rollback.php
- cli-upgrade.php
- tests/unit/ErrorHandlerTest.php
:heavy_check_mark:  Waiting for #727 to be merged first
| Description?      | We found out in some workflow, an exception not handled would still return the error code 0, allowing the next steps to be run. This PR makes sure a non-zero code is returned.
| How to test?      | CI must be red if an issue is triggered by a module for instance.
PR contents:
* Returns a non zero code when an exception is not handled
* Remove html contents (displayed on CLI which is a non-sense)
* Allow process to continue on error during updates
* Display error …
> Return exit code on unhandled exceptions, and allow process to go on when upgrading a module fails

- .github/mktp-metadata.json
- .github/workflows/build-release.yml
- .github/workflows/publish.yml
- autoupgrade.php
| Description?      | Improve release process in GH workflows
> Improve release process in GH workflows

- classes/UpgradePage.php
- js/sentry.js
| Description?      | From the first tests, it appears anything reported on the backoffice when on the upgrade page can be sent to our Sentry project. This PR filters the errors that only triggered from the feedback modal and add useful informations for triage and debug.
| How to test?      | Try manually sending an error to Sentry (or with `Sentry.captureMessage()`). It won't be taken in account.
* Add the concerned release of the module
* Add attachments: Contents of logs panel + Contents of error panel
> Make sure only the errors by merchants are sent to Sentry to avoid noise from the rest happening on the BO

- classes/UpgradePage.php
- js/upgrade.js
| Description?      | Removing the ability to save a channel archive without zip and xml
| How to test?      | Save archive config without zip and xml
> Removing the ability to save a channel archive without zip and xml

- classes/Progress/CompletionCalculator.php
| Description?      | While upgrading, we see some notices about a implicit float cast as integer. This PR fixes the issue.
| How to test?      | There is no more notices in the logs when running steps like UpgradeFiles or BackupFiles
> Cast explicitely percentage as integer

- .php-cs-fixer.dist.php
- autoupgrade.php
- classes/UpgradeContainer.php
- classes/UpgradeTools/Translator.php
- storybook/.storybook/global.d.ts
- storybook/.storybook/main.ts
- storybook/.storybook/preview.ts
- storybook/config/services.yaml
- storybook/src/EventListener/LocaleListener.php
- storybook/src/Translation/TranslatorBridge.php
- storybook/src/Translation/TranslatorFactory.php
- storybook/stories/Main.stories.js
- tests/fixtures/ModulesAutoupgradeAdmin.fr.xlf
- tests/unit/UpgradeTools/Translator/TranslatorTest.php
| Description?      | Allow the translations to be used when using Storybook, allowing the templates to be multi languages while working on them. This PR also removes the use of PrestaShop constants in the `Translator` class, making it unit-testable and usable outside the BO context.
| How to test?      | Translations are still available on the module in the BO (non-regression tests), and you can now switch on another language from the top bar of Storybook.
[Capture vidéo du 2024-07-17 …
> Make module Translator usable on Storybook

- controllers/admin/AdminSelfUpgradeController.php
| Description?      | Quick fix on a controller display on V9 after an upgrade. A new context mechanism is present on v9, and on old controllers the constructor is called before the listenners to avoid context overload (https://github.com/PrestaShop/PrestaShop/blob/f55bf596ba0a12e22846d706ac0834be8ebf0e45/src/PrestaShopBundle/Routing/LegacyRouterChecker.php#L117). After an upgrade we disconnect the user from the session, and the employee context is null. Before 9 we were redirected before arriving at the controller, but in v9 we call the constructor and the init method to initialize the context on LegacyRouterChecker, and we have an error because the init method calls …
> Improvement for new v9 context

- controllers/admin/AdminSelfUpgradeController.php
| Description?      | Fixed bad parameter when updating configuration
> Fixed bad parameter when updating configuration

- classes/Twig/Block/UpgradeChecklist.php
- classes/UpgradeSelfCheck.php
- classes/VersionUtils.php
- tests/unit/UpgradeSelfCheckTest.php
- tests/unit/VersionUtilsTest.php
| Description?      | Removing patch version when comparing php version for destination version
| How to test?      | try to update to Prestashop 8.1.7 (php requirement 7.2.5) with php 7.2.1x
> Removing patch version when comparing php version for destination version

- classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php
- tests/unit/UpgradeTools/CoreUpgrader/CoreUpgraderTest.php
| Description?      |  Improve runPhpQuery readability and parameters extraction. Add unit tests. this function is responsible for retrieving php functions executed in SQL scripts
| How to test?      | PHP function in sql files works the same way as before
> Improve "runPhpQuery" method

- classes/Analytics.php
- classes/Parameters/UpgradeConfiguration.php
- classes/Twig/Form/UpgradeOptionsForm.php
- controllers/admin/AdminSelfUpgradeController.php
- tests/unit/AnalyticsTest.php
- tests/unit/Progress/CompletionCalculatorTest.php
| Description?      | Drop server performance configuration
> Drop server performance configuration

- .github/workflows/js.yml
- _dev/vite.dev.config.ts
- classes/Router/Router.php
- composer.json
- composer.lock
- controllers/admin/AdminSelfUpgradeController.php
- controllers/admin/self-managed/AbstractGlobalController.php
- controllers/admin/self-managed/AbstractPageController.php
- controllers/admin/self-managed/WelcomeController.php
- storybook/.storybook/main.ts
- storybook/package-lock.json
- storybook/package.json
- storybook/stories/components/RadioCard.stories.js
- storybook/stories/layouts/Layout.stories.js
- storybook/stories/layouts/Welcome.stories.js
- views/templates/components/radio-card.html.twig
- views/templates/layouts/layout.html.twig
- views/templates/layouts/welcome.html.twig
| Description?      | This PR add first page of new UI.
| Type?             |  new feature
| How to test?      | Go to configuration page of module and add `&new-ui=1&route=welcome` at the end of the URL.
> Feat: connect new UI

- classes/Twig/Block/UpgradeChecklist.php
- classes/UpgradeSelfCheck.php
- views/templates/block/checklist.html.twig
| Description?      | Withdrawal of the requirement. We decided to remove it because the user will inevitably have errors before arriving on the module configuration page. The Prestashop back office requires PHP sessions, 
> Drop "isPhpSessionsValid" requirement
